### ISSUE TITLE
Crash on some systems

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#1]
Two people can run successfully, two people crash at launch.

Both crashes log ends with:

`Shader code info from D3DCompiler_xx.dll wrapper received:
  Bytecode hash = 0bff0cd0b2fc3f63
  Filename = 0bff0cd0b2fc3f63-vs_4_0_275bfe003bca8ef5.txt
`

In success case, it's:

`Shader code info from D3DCompiler_xx.dll wrapper received:
  Bytecode hash = 0bff0cd0b2fc3f63
  Filename = 0bff0cd0b2fc3f63-vs_4_0_275bfe003bca8ef5.txt`

`D3D11CreateDeviceAndSwapChain called with adapter = 0
  CreateDeviceAndSwapChain returned device handle = e07635c, context handle = e0769bc
  creating NVAPI stereo handle. Handle = 2abcca8
  creating stereo parameter texture.
    stereo texture created, handle = e037c50
  creating stereo parameter resource view.
    stereo texture resource view created, handle = e068384.
  returns result = 0, device handle = e07635c, device wrapper = df95900, context handle = e0769bc, context wrapper = e062c80`

That suggests pretty strongly that it is crashing with CreateDeviceAndSwapChain.

**Comment by DarkStarSword** [comment]
As far as I am aware, all known crashes with Steam, UPlay and Origin overlays are fixed - closing.

**Comment by bo3b** [comment]
Yep, worth closing, the fundamental problem here was no support for platform update (evil). We can handle either with or without now.

If we ever see any further overlay problems we can open a new issue.

**Comment by bo3b** [comment]
![image](https://cloud.githubusercontent.com/assets/6544511/22624161/934dba64-eb27-11e6-8f78-46c902e96e1b.png)

Using this old closed issue to store the 3Dmigoto logo, as I see the website has gone offline.
