### ISSUE TITLE
Crash on intra-device resource copy & inappropriate [Constants] re-run

### ISSUE THREAD

**Issue by DarkStarSword** [bo3b/3Dmigoto#101]
This is happening with an older version of the "SSR Event New Year 2019 Mikomai" mod when the news is opened in DOAXVV (the news uses an embedded Internet Explorer widget that only works in windowed & borderless fullscreen modes). More recent versions of this mod have worked around the issue by using [Present] instead of [Constants], but the underlying issue remains (and doing excessive full copies inside [Present] is bad for performance). The debug log is noisy with output from multiple threads intermixed and is 200MB long even if only activated a frame or two before opening news, so summarising instead:

- **The existing device and context continue to be used, with draw commands, etc. being submitted through them throughout this entire sequence**.
- Loop 8 times (not sure why - haven't spotted a difference between the logs, but the intermixed log with the other context makes it difficult):
  - CreateDXGIFactory1(IDXGIFactory2)
  - D3D11CreateDevice(..., ppImmediateContext = NULL)
    - Create device specific 3DMigoto StereoParams & IniParams resources and views
  - Device QueryInterface(ID3D11Device1)
  - GetImmediateContext
    - Wrap new immediate context
    - Bind 3DMigoto resources to new context
    - **[Constants] command list run**
      - *Mod submits GPU commands to make full copies of certain existing resources*, **using this device & context, which is not the device & context the source resources were created with**:

            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto  [Constants] run = commandlistloaddefault
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto  pre {
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto   [commandlist\mods\costumes\crash ssr event new year 2019 mikomai\honoka luna.ini\loaddefault] if $honoka_luna_mikomai_top == 0: true {
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto    [commandlist\mods\costumes\crash ssr event new year 2019 mikomai\honoka luna.ini\loaddefault] run = commandlist0
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto    pre {
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto     [commandlist\mods\costumes\crash ssr event new year 2019 mikomai\honoka luna.ini\0] resourcetopvb = resourcemodtopvb
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto       performing full copy
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto     [commandlist\mods\costumes\crash ssr event new year 2019 mikomai\honoka luna.ini\0] resourcetopib = resourcemodtopib
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto       performing full copy
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto    }
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto   } endif
            FrameAnalysisContext(class FrameAnalysisContext@0000022A1A8AB5A0)::3DMigoto  }
  - Context QueryInterface(ID3D11DeviceContext1)
  - Device QueryInterface(IDXGIDevice2)
  - Release new devices & contexts (refcount on context is still 1)
- The actual crash occurs while the main context is mid-way through a log despite unbuffered=1, because of multi-threading.

I don't see anything particularly special about the 8th new device & context they create compared to the first 7, nor are the suspect resources identified in this sequence used back in the main context (the mod is installed, but the costume it alters is not active), but given the asynchronous nature of DirectX this crash could be something done earlier finally catching up with us.

There are several issues I see from this sequence that we need to look at:
- Re re-run the [Constants] command list for each new device & context, which may be an issue since we are resetting various variables & resources back to default. [Constants] is only intended to be run once on program load & config reload, though the convoluted mess with multiple / temporary DirectX devices & contexts used by some games at startup may complicate that goal.
- We perform an inter-device resource copy without any flags set up to allow this (this is most likely what is actually causing the crash, all but confirmed by changing this to a copy-by-reference which resolves the crash)
- [resourcetopvb] and [resourcetopib] will now point to a resource created via this new device instead of the main device, which may be problematic if they are later used on the main device because, again they lack the flags to allow resource sharing between devices.

My immediate thought is that we could enable resource sharing between DirectX devices, but I'd need to see what consequences that may have (Any issues with performance? What happens if the refcounts are messed up on a shared resource? Is it still released at program termination, when all devices that use it are destroyed, when the device that created it is destroyed or could it live on?).

Another possibility is that we could check what device was used to create a custom resource and recreate it if necessary (e.g. extend RecreateCompatibleResource() & the resource pool to consider the creation device as well as the resource description), however one custom resource holding a reference to another won't know how to recreate itself after the fact and we could end up with a blank resource - in this case that would probably work since the proposed extension to the resource pool would switch back to the original resource when we go back to the original device & context, but this may not be the case with games featuring convoluted start-up sequences involving multiple throwaway devices & contexts.

We could also add a special case for an inter-device resource copies that use intermediate resources with the required flags enabled. I'd need to check the doco for what is required to make this work - IIRC the device itself needs a special flag set at creation time.

We also need to look at stopping [Constants] from re-running when a new context is created, but doing that by itself may be problematic for games that create 12 devices & contexts on launch and discard the first 11 unless we have also resolved the inter-device resource sharing issue.

(For the mod author): Probably a better workaround for this issue until it is properly fixed in 3DMigoto is to perform the copy by reference (i.e. "resourcetopvb = ref resourcemodtopvb" and ditto for the ib) instead of putting it in [Present] - that should avoid the inter-device copy.

**Comment by DarkStarSword** [comment]
Making a note of this here while I think of it: The IniParams GPU resources are all per-device, but the IniParams CPU buffer is shared between all devices. The command list and keyboard processing code updates the IniParams GPU resource whenever a change is made to the CPU buffer, but only for the GPU resource attached to the device associated with that change (i.e. the device used for the Present() call, or the device used to draw a certain shader that triggered a command list, etc).

For the most part this works fine so long as there is only one device doing all the work, but if a game were to use multiple devices and the updates got split over different devices (e.g. such as [Constants] being run on a different device as in the scenario in this issue) 3DMigoto would only update the IniParams GPU resource on that device, and the other devices would see stale values.

**Comment by DarkStarSword** [comment]
According to:
https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/ne-d3d11-d3d11_resource_misc_flag

the only resources that can be shared between devices are 2D non-mip-mapped resources, making that possible solution a non starter since the resources being copied in this case are vertex and index buffers.

**Comment by bo3b** [comment]
> According to:
> https://docs.microsoft.com/en-us/windows/desktop/api/d3d11/ne-d3d11-d3d11_resource_misc_flag
> 
> the only resources that can be shared between devices are 2D non-mip-mapped resources, making that possible solution a non starter since the resources being copied in this case are vertex and index buffers.

For doing arbitrary resource copying, you might want to take a look at Cuda copies.  This keeps everything on the GPU, and gives you a more generalized API.  However, I do not understand the nuances here, so may not apply in the scenario.

**Comment by DarkStarSword** [comment]
Looking at some documentation for OpenCL it appears the same resource sharing flag is required there, which would seem to have the same limitations as for resource sharing between DirectX devices (and the examples I looked at were all sharing 2D resources and indicated there were limitations in what resources could be shared).

At this point I'm thinking that the general way to solve this will be to stage the resource to the CPU and copy it that way, which is certainly far from ideal and would only be acceptable in rarely used slow paths - fortunately rarely used slow paths are by far the most likely circumstance where we would encounter this situation, and momentarily stalling the pipeline is still objectively better than crashing.

The concern would be if there are any circumstances where this could happen in a fast path (e.g. a resource created on a different device being accessed once/frame), but given that this would lead to a crash today it would seem to be unlikely (unless it is somehow being masked), and we can highlight these extra slow copies in the performance monitor and if they ever show up look for ways to avoid them, or add an option to disable inter-device copies in favour of discarding/recreating the affected resources.

**Comment by DarkStarSword** [comment]
Closing now that 1.3.15 is out

**Comment by DarkStarSword** [comment]
Reopening this - there are reports of conflicts with the latest ReShade, that seems to force some buffers to be dynamic that are not supported by the inter-copy as yet.

**Comment by DarkStarSword** [comment]
Closing now 1.3.16 is out
