### ISSUE TITLE
Can't "handling = skip" TextureOverride, bug or am I doing something wrong?

### ISSUE THREAD

**Issue by WinkelCode** [bo3b/3Dmigoto#102]
TextureOverrides don't seem to want to work (no error but also no effect) although it works perfect while hunting and the hash doesn't change:

```
[TextureOverrideTest]
hash = d9fe85cc
handling = skip
```

This is in the log:

```
[TextureOverride\Mods\test\test123.ini\Test]
  Hash=00000000d9fe85cc
  handling = skip
```

I know for a fact it is detected, duplicating it in the main configuration (Edit: where it also doesn't work) will trigger the duplicate warning, also intentionally removing a letter will also trigger an error.

Shaders work perfectly while hunting and in the same configuration file as used before:

```
[ShaderOverrideTest]
hash = c9f75abb67053172
handling = skip
```

Log:

```
[ShaderOverride\Mods\test\test123.ini\Test]
  Hash=c9f75abb67053172
  handling = skip
```

Edit: More Info:

- I tried with default config and only the [TextureOverrideTest] block.

- I have the general method used here from the first part of this video (although I am testing it in a different, Unreal Engine 4 based game "Train Sim World", if that matters): https://www.youtube.com/watch?v=zWE0xP4MgR8 - Does he maybe have something in the config that is required for skipping "Textures" (I am just using basing off of default one that comes with 3Dmigoto)? I am especially curious about all the zeroes before the hash in the log.

**Comment by martinsstuff** [comment]
(To see how everything works I am removing the playermodel from the game's main menu)

I think I understand now, so I basically have to go through all the shaders until I can piece together the elements making up the model and only then I can apply the TextureOverride onto those shader elements so it doesn't have to test against all elements in the scene. Is this correct?

**Comment by DarkStarSword** [comment]
Yes, that is correct.

**Comment by DarkStarSword** [comment]
If you want a quick way to activate all TextureOverrides on a given slot regardless of shader you can use a match all ShaderRegex section, like:

    [ShaderRegexEnableVB0TextureOverrideWildcard]
    shader_model = ps_4_0 ps_5_0
    checktextureoverride = vb0

This will result in extra work performed in every draw call, so may impact the framerate when CPU bound (even more so for users with slower CPUs) and therefore it is recommended to identify the specific relevant shaders.

Note that ShaderRegex will not match any shaders found in ShaderFixes.
