### ISSUE TITLE
Add support for vendor extension draw calls

### ISSUE THREAD

**Issue by DarkStarSword** [bo3b/3Dmigoto#103]
Resident Evil 2 uses the vendor extension draw call NvAPI_D3D11_MultiDrawIndexedInstancedIndirect, which is documented here along with NvAPI_D3D11_MultiDrawInstancedIndirect:

https://docs.nvidia.com/gameworks/content/gameworkslibrary/coresdk/nvapi/group__dx.html#gaf417228a716d10efcb29fa592795f160

3DMigoto will miss draw calls made via this API, meaning no ShaderOverride support, ShaderRegex, hunting (skip mode), stats, etc.

However, while I haven't looked at this in person as yet, the reports I'm seeing on Discord suggest that the 3D Vision driver also misses this call so geometry drawn through it is only rendered in one eye, meaning just adding support for this as an extra draw call in 3DMigoto would be insufficient to make it work in 3D. Reimplementing it in terms of the standard DirectX draw calls would work, but would defeat the point of using the vendor extension in the first place.

Resident Evil 2 also has a config option to disable vendor extensions (`UseVendorExtention=Disable`
 in re2_config.ini), making this a low priority.

**Comment by DarkStarSword** [comment]
Schwing coded up a DLL that would reimplement these in terms of the standard DX draw calls, thereby allowing them to work in RE2 without having to change the options, as well as making a custom 3DMigoto build for other RE2 issues. I've asked him to join the 3DMigoto dev team to integrate his changes in 3DMigoto and we can look at moving the functionality from his DLL into our nvapi wrapper.

**Comment by Schwing-Man** [comment]
That was a rough draft approach of using memory writes to reroute RE2's call from the original MultiDraw...() to the exported one I created in d3d11.dll. The real approach will be how 3Dmigoto is wrapping functions, plus the need for 3Dmigoto's nvapi64.dll to call its d3d11.dll. The R410 version of the nvapi will be needed, or any version that has MultiDraw...() defined in nvapi.h.

**Comment by Schwing-Man** [comment]
The proper implementation is complete. It's just NVAPI project changes. Per Discord, I'll need to update it before uploading it to support the second of the two MultiDraw() fn's. Also log bloat prevention by having it only occur when verbose logging is enabled.

**Comment by Schwing-Man** [comment]
[commit 27bf496](https://github.com/bo3b/3Dmigoto/commit/27bf4969b567b1c5ab4a8e26ef79402d31497520)

**Comment by Schwing-Man** [comment]
The changes are set for the next release.

**Comment by DarkStarSword** [comment]
Closing now that 1.3.15 is out
