### ISSUE TITLE
Do something if a texture is rendered

### ISSUE THREAD

**Issue by Kame-Man** [bo3b/3Dmigoto#109]
Hello

Sorry if this is a wrong place to ask such questions but let's say i want to hide a certain texture ingame if another is visible on the screen.
I tried with the code below but perhaps my understanding of filter_index is totally wrong:

[ShaderOverride icons]
Hash = cee39063f97c5030
checktextureoverride = ps-t70

[TextureOverride adrestia icon]
Hash = 8f9f2ffc
filter_index = 5999  ; just typed a random number

[TextureOverride player icon]
if ps-t70 == 5999
Hash = e9f100b5
Handling=skip
endif

So is filter_index a way to tag a texture so it can be used in functions like above with "if ps-t70 == 5999" for instance, or am i completely wrong here ? 
If not what would be the best way to complete this task

I'm trying to disable some floating icons that cannot be disabled in the game hud options. Disabling their textures (skipping) with 3d Migoto makes them also disappear from the menus, i found a nice way to get around this for the mouse and keyboard with if !cursor_visible conditional check, but sadly it wont work for game controllers as their "cursor" moved by analog doesnt register as a cursor like it does for the mouse.
I figured that if i could check if the controller cursor texture is displayed i could make it work for the controllers as well, just don't know how.
The above function was just a failed check to see if i can make it working

**Comment by Kame-Man** [comment]
Anyway if this is a silly question and a wrong place to ask, could you let me know if there is a 3D Migoto forum or some other place where i can ask such questions?

**Comment by bo3b** [comment]
Yes, this is not the best spot to get an answer. This is more for longer term issues with 3Dmigoto, like bugs or feature requests.

Best place to get help on using the tool would be on the Discord channel for 3D.  Look on HelixModBlog for the link.

**Comment by Kame-Man** [comment]
Yes well i just literally couldnt find any 3D Migoto forum so i figured I'd ask here, naughty me... You can remove this if possible thanks 😀
