### ISSUE TITLE
SR3

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#11]
#### Game Fix Notes
1. Must delete the profile (320.49)  With the default, useless profile, it damages the image like nothing is being loaded.  An empty profile works fine.
2. Must use SLI.  ? Without SLI setup, I was getting haloing in SR3 and SR4, around stuff like furniture and the main character.  Seems unrelated to the main fix we make which is to stereoize all the textures, but maybe there are other shaders that only run in non-SLI.

![non-sli halo saintsrowthethird_dx1112_85](https://cloud.githubusercontent.com/assets/6544511/3269294/abdb7e96-f2ea-11e3-8d6e-509202f4bb1b.jpg)
1. Primary fix was done with auto-mode on migoto, where it auto-fixes any textures that need to be steroized as well.  This fixes some 1500 shaders.
2. Next significant fix is the lights.  Using Mike's example, I got a lights working in the crib, where it shines on the wall.  
3. Moon/skybox are not quite clear yet, but best fix seems to be x += st.x \* (-st.y).

**Comment by DarkStarSword** [comment]
Most likely needed StereoFlagsDX10=0x00004000 for non-SLI case. Closing this, as it is not a 3DMigoto issue.
