### ISSUE TITLE
can't override textures

### ISSUE THREAD

**Issue by Doodlezoid** [bo3b/3Dmigoto#116]
I'm trying to override an unused texture in a shader so that I can inject a LUT texture. 

I've added these lines:
[ResourceReplaceTexture1]
filename = ShaderFixes\LUT.jpg

[ShaderOverride1]
Hash = 79ad392997e08cfd
checktextureoverride = ps-t0

[TextureOverrideLUT]
Hash = f3d023b3
ps-t0 = ResourceReplaceTexture1

But the texture isn't being replaced.

shader filename is 79ad392997e08cfd-ps_replace.txt
texture i want to replace is Texture2D<float4> g_diffuseTexture : register(t0);
dumped texture filename  002043-ps-t0=f3d023b3-vs=94de601497014a49-ps=79ad392997e08cfd.jpg

**Comment by DarkStarSword** [comment]
That looks correct to me. Try enabling track_texture_updates (game restart required) and see if you get a different texture hash. There's a performance penalty associated with that option, but in some games it is the only way to reliably match textures.

**Comment by DarkStarSword** [comment]
If you don't mind I'm going to close this issue. If you require further assistance please ask on the shaderhacking or 3DMigoto channels on our Discord: https://discord.gg/tXHYhNK or on the GeForce forums: https://forums.geforce.com/default/board/49/3d-vision/
