### ISSUE TITLE
Deus Ex: Mankind Divided freezes after cycling through first shader

### ISSUE THREAD

**Issue by AlexDemolisher** [bo3b/3Dmigoto#118]
Either pixel or vertex, forward or backwards, cycling through shaders freezes game after 1-2 clicks (and windows, needs hard reboot). Win7

**Comment by DarkStarSword** [comment]
The game is likely feeding the output of one shader into another that causes a driver crash if it is not initialised due to skipping the first shader. Try a different marking_mode, such as mono or pink, or exclusively use frame analysis instead of hunting.

**Comment by AlexDemolisher** [comment]
Turns out it works with everything, but pink. Strange.

**Comment by DarkStarSword** [comment]
Yeah, some games can be finicky like that. Good to know it's working with other modes. Closing the issue.
