### ISSUE TITLE
Range of Floating-Point Type (float) exceeded in export

### ISSUE THREAD

**Issue by thrive4** [bo3b/3Dmigoto#120]
Reference:
https://docs.microsoft.com/en-us/cpp/c-language/type-float?view=vs-2019
'Type 	Minimum value 	Maximum value
float 	1.175494351 E - 38 	3.402823466 E + 38'

Code:
https://github.com/bo3b/3Dmigoto/blob/master/D3D_Shaders/Assembler.cpp
Line 73 (starts at)

Export in shader:
r13.yw = float2(4.20389539e-045,2.80259693e-045); 

Context:
Game wrc 6 running on win 7 / dx11 nvidia 1050 gtx ti 382.05 (driver)
export is the same on 3dmigoto v1.3.11 ad well v1.3.16 (current version)

Hope this is sufficient info basically came across this issue when tweaking
the shader and started noticing how distance shadows popped in severely.
1166d89e180b5f47-ps_replace.txt

First thought it was caused by the tweaks I made to the shader but then
run the game with an unaltered export, which was neatly compiled by 3dmigoto,
and the pop in stayed the same.

Then altered the export from:
r13.yw = float2(4.20389539e-045,2.80259693e-045); 
to:
r13.yw = float2(4.20389539,2.80259693);
and it stopped.

I think and hope that this is a edge case.
Would like to take this opportunity to thank all the people involved
in making and sharing 3dmigoto it really is a wonderful proxy.

**Comment by DarkStarSword** [comment]
Please attach the original unmodified binary shader to the bug report. Add the option export_binary=1 under [Rendering] in the d3dx.ini to export these.

Please note that the minimum non-zero value a 32bit floating point value can store is in fact ~1.4e-45 (represented by 0x00000001), well below the ~1e-38 minimum quoted in the article, which only applies to normalized floating point values. These very small values are called "subnormal" or "denormalized" numbers and are stored with the biased exponent field set to 0, and do not have the implicit high bit in the mantissa.

The values that you have quoted are in fact:
4.20389539e-045 = 0x00000003
2.80259693e-045 = 0x00000002

If you have Python installed you can use my float_to_hex.py script to check these cases:
https://github.com/DarkStarSword/3d-fixes/blob/master/float_to_hex.py

It therefore appears that you are dealing with a shader that is not actually using floating point and It is therefore incorrect to replace these values with 4.2 and 2.8, as they should in fact be 3 and 2 respectively. Note that our decompiler does not cope well with shaders using integer data types and you may be better off using the disassembler/assembler workflow for these shaders, especially if this is more than a one off anomaly.


The code you have referred to in Assembler.cpp is not relevant to this case. That code is used to correct precision issues in disassembled code, where Microsoft's disassembler outputted insufficient decimal digits to reconstruct the original floating point value precisely. Funnily enough, I note that the article you quoted includes a similar mistake to their disassembler, documenting that a float has 6-7 significant digits, when in reality it has 24 significant binary digits, which translates into 8-9 significant decimal digits, with 9 significant decimal digits being required to accurately reconstruct the original float.

**Comment by thrive4** [comment]
Well ok so an edge case, still curios why the shadow
popping stopped after the alteration but there it is.
Thanks for your time and detailed response.
On a small side note those hex numbers are vaguely familiar
to hbao flags 0x00000003, etc.
