### ISSUE TITLE
SR1

### ISSUE THREAD

**Issue by DarkSagaBR** [bo3b/3Dmigoto#123]
Good night I've mooded sr1, tough being restriked by the injector, could this shader be used with reshade to load textures on that game? pc version? if so could explain how? Thanks... it's dx6 tough it runs dx11 wraped by voodoo and reshade does take readings as dx11...

**Comment by THELASTOFUS** [comment]
goodnight to you too...

**Comment by DarkStarSword** [comment]
@DarkSagaBR I'm afraid I can't understand what you are trying to ask. It might be easier to jump on #3DMigoto on Discord and ask there: https://discord.gg/eR9KAnz

For now I'm closing this bug report, since it isn't a bug report.
