### ISSUE TITLE
Monster Hunter World game update has broken 3DM ability to hook. 3DM Loader compatibility Issues as well

### ISSUE THREAD

**Issue by DJ-RK** [bo3b/3Dmigoto#127]
One of the MHW game updates from earlier this year has broken fix compatibility. The game now prevents 3DM's ability to naturally wrap via placing the d3d11.dll in the game's directory. The game just loads, completely ignoring it's existence. No log gets generated (even with debug and unbuffered options enabled). Attempted most of the various hooking options available in the d3dx.ini file without success. Interestingly enough, ReShade can still hook in via it's dxgi.dll. I tried the dxgi.dll version of 3DMigoto and it still couldn't hook.

To workaround this, I had success getting the 3DMigoto loader to hook in via finding the matching process name. All was well (for me), however several users reported that it would not work for them, and the game would silently crash.

I performed some testing, could reproduce the issue on fresh Windows installations, and found that updating my Visual C++ 2013 redistributable resolved the issue for me, but not for other users.

Further detail can be found on MTBS3D from reading this post onwards: https://www.mtbs3d.com/phpbb/viewtopic.php?p=171659#p171659

and I've requested support on Discord here: https://discord.com/channels/515703864616288257/515704137795633154/727287226513489971

This is likely a game specific issue, rather than a bug or issue with 3DM per se, but figured documenting it here as well would be prudent.

**Comment by Schwing-Man** [comment]
Closed: worked with DJ-RK to find that it's the game's insane anticheat functionality blocking the d3d11.dll from being used when the game attempts to load it. The game then uses the original dll. The workaround is to use 3DMigoto Loader outside of the game directory.
