### ISSUE TITLE
Add nvapi functions like force automatic

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#16]
Make sure these work in latest versions.  

Force automatic mode, to disable built-in renderers.

Force 3D on, regardless of profile.

Force convergence unlock.

Iron sight aiming override.  Multiple keys mapped.

Force specific refresh rate and resolution.

**Comment by DarkStarSword** [comment]
> Force automatic mode, to disable built-in renderers.

Working.

> Force 3D on, regardless of profile.

Working.

> Force convergence unlock.

AFAIK this is working.

> Iron sight aiming override. Multiple keys mapped.

Obsoleted by new input infrastructure.

> Force specific refresh rate and resolution.

AFAIK this is working.


Closing this one out.
