### ISSUE TITLE
Unpacked conditionals can damage destination.

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#17]
"movc_sat r2.xyzw, r2.xxxx, r7.xyzw, r4.xyzw" 

into 4 line of HLSL

  // r2.x = saturate(r2.x ? r7.x : r4.x);
  // r2.y = saturate(r2.x ? r7.y : r4.y);
  // r2.z = saturate(r2.x ? r7.z : r4.z);
  // r2.w = saturate(r2.x ? r7.w : r4.w);

Where the r2.x is damaged after the first line, and no longer valid.

Could also become:
  r2.xyzw = saturate(r2.xxxx ? r7.xyzw : r4.xyzw);

**Comment by bo3b** [comment]
This has been fixed, but it's not clear if the fix is always correct.

I rolled the conditionals back into a single instruction.

Asked Chiri about this specifically, and he said that he ran into a situation where he needed to unroll the conditional.  I haven't seen any negative effects from re-rolling them back up, but it's worth keeping open as a 'maybe.'

**Comment by DarkStarSword** [comment]
Closing this - if there ever are any negative side effects discovered we can reopen it then.
