### ISSUE TITLE
Duckstation shaders

### ISSUE THREAD

**Issue by duig0** [bo3b/3Dmigoto#170]
hello,

i wonder if anyone can help

i am trying to disable the player model in game

i can do so, however the shader is also responsible for other oblects

in short disabling the shader disables too much lol

is it possible to alter the shader to remove only what you want and leave the rest?

and if so, is there a guide on how,to do so?

many thanks in advance

**Comment by DarkStarSword** [comment]
Try matching on index and/or vertex buffer. Something like:

```
[ShaderOverrideBlah]
; Fill in the relevant shader hash here:
hash = ...
checktextureoverride = vb0
checktextureoverride = ib

[TextureOverrideBlah]
; Fill the index buffer or vertex buffer hash here:
hash = ...
handling = skip
```

numpad 7/8/9 hunt index buffers, and numpad /*+ hunt vertex buffers. If `marking_actions=clipboard` is enabled marking the buffer will copy the hash to the clipboard, or enable `verbose_overlay=1` to see it on the OSD.

> and if so, is there a guide on how,to do so?

Unfortunately we effectively lost a lot of our old documentation and guides when nvidia migrated forums a few years ago :(
You can still find links to some of our old doco in the guides section at the bottom of this page: https://helixmod.blogspot.com/2013/10/game-list-automatically-updated.html
