### ISSUE TITLE
Genshin 3Dmigoto

### ISSUE THREAD

**Issue by Smasher3011** [bo3b/3Dmigoto#174]
Greetings sir, for couple of days I used 3dmigoto without any issues but suddenly it does not work in my genshin.I have tried reinsatlling from 0 but it didn't work. What can I do?

**Comment by DarkStarSword** [comment]
In that case I'll close this ticket, but if the issue turns out to be in 3DMigoto itself feel free to re-open it - I'm planning to do a new point release at some point in the near future and could include any necessary bug fixes for this.
