### ISSUE TITLE
Apply shaderfixes on specific objects

### ISSUE THREAD

**Issue by dnblank123** [bo3b/3Dmigoto#184]
Hi, so I'm trying to fix a shader bug on a game, specifically particle misalignment. I tried modifying the shader:
  `r7.xyz = r8.xyz + r7.xyz;` to  ` r7.xyz = r8.xyz * r7.xyz;`  and the result is on the 2nd image, the fire got affected (since it shares the same shader). So my question is, is it possible to modify specific object only? or is there a better way to handle this?
  
 Shader file.
[f1935ee57227f0aa-vs_replace.txt](https://github.com/bo3b/3Dmigoto/files/13327442/f1935ee57227f0aa-vs_replace.txt)

[Trying to fix]
![particle-misalign](https://github.com/bo3b/3Dmigoto/assets/67945097/051ed3cf-1dc8-4152-8acc-516d7fa55017)

[When applying a "fix", the particle in the sword is fixed but the fire changed.]
![applied-shader](https://github.com/bo3b/3Dmigoto/assets/67945097/6fe2e7ae-91ed-4d36-8344-721a2c1fc06a)

**Comment by DarkStarSword** [comment]
Configure 3DMigoto for mesh hunting. Find these settings in the d3dx.ini and configure them similar to the following (this enables both hunting + frame analysis. You don't strictly speaking need both, but they are both useful in different ways):

```
; Set to 1 or 2 depending on preference:
hunting = 1

; Set to 1 to see the hash in the overlay. I don't recommend transcribing it from there, but it's still useful to see:
verbose_overlay = 1

; Rather, I recommend including clipboard in this setting so you can copy the hash directly.
; Feel free to include any other options you want as well:
marking_actions = clipboard

; Uncomment this if you want to use the frame analysis feature to dump meshes:
analyse_frame = no_modifiers VK_F8

; Minimum options required to dump meshes with frame analysis.
; I usually also turn on dump_ib and buf in case I need the raw binary buffers for some reason.
; In games that use multi threaded rendering you may also need to add deferred_ctx_accurate.
; You might also consider dump_rt to dump the render targets after every draw call to help work
; out which draw call was related to the object of interest - however this makes the dump take a
; lot longer, use a lot more disk space, and most of the render targets will be dumped as dds files
; that very few image viewers can open, so I only enable that if I need it.
analyse_options = dump_vb txt
```


Find the vertex buffer of the object you want to adjust either via hunting (numpad /* to cycle, numpad - to copy selected vertex buffer hash to clipboard), or frame analysis (with hunting overlay shown press F8, then refer to the files dumped to the timestamped FrameAnalysis folder in the game directory. You can use my [blender addon](https://github.com/DarkStarSword/3d-fixes/blob/master/blender_3dmigoto.py) to import these to Blender)

Configure the shader you found earlier to enable TextureOverride checks on the vertex buffer. Note that I've put the hash from your attached vertex shader here, but I would generally recommend doing this with the pixel shader hash instead - pixel shaders tend to be a bit more specific to certain objects/materials than vertex shaders (it's also possible to add partner shader filtering to match a combination of a specific vertex and pixel shader being used together, though this is only rarely more useful than matching a pixel shader alone).
```
[ShaderOverrideShoesVS]
hash = f1935ee57227f0aa

; Since you are modifying the shader you need a variable to tell which object it is currently drawing.
; This will set x (accessed in the shader as IniParams[0].x ) to the filter_index of the TextureOverride
; that matches the currently bound vertex buffer in slot 0:
x = vb0

; Alternatively, if you wanted to take some action when the vertex buffer is matched you would use this to
; run any command lists in the TextureOverride section that matches the currently bound vertex buffer 0, the
; most common use case for this is to modify meshes with the blender addon and re-inject them into the game
; - find my costume modding tutorial on youtube for more details on this:
;checktextureoverride = vb0
```

Now that you have enabled either vb0 filtering or TextureOverride command lists from that shader, add a TextureOverride section to match the piece of the mesh you want to modify:
```
[TextureOverrideShoes]
hash = ...

; If the mesh is broken up into multiple pieces (usually for different materials) you can also use this to match a
; specific sub piece. Find this value in the text files for the mesh dumped with frame analysis, or if you use my
; blender addon to import it to blender you can find this in the custom data attached to the object:
; match_first_index = ...

; This will be the value that this texture will evaluate as in the x=vb0 above. Default is 1 if not specified (0
; signifies no TextureOverride section matched, -0.0 indicates no resource was bound to the slot at all), so
; usually you want to set this to 2 or above, either as a unique number for each item, or grouping items you
; want to apply the same adjustment to:
filter_index = 2
```

**Comment by dnblank123** [comment]
Hi, thanks for replying, I'm getting an error for undeclared identifier 'IniParams', also is the partner filtering correct? I assume that `x = vs` will automatically direct to vs?
```
[ShaderOverrideParticleVS]
Hash=f1935ee57227f0aa
x = ps-t0
[ShaderOverrideParticlePS]
Hash=50c511b571100ded
x = vs 
[TextureOverrideSwordParticle]
hash = 6b03d923
filter_index = 206501
```
then in the shader `f1935ee57227f0aa-vs_replace.txt`

```
// 3Dmigoto declarations
#define cmp -
#define test IniParams[0].x
...
  if(test == 206501)
  {
    r7.xyz = r8.xyz * r7.xyz;
  }
  r7.xyz = r8.xyz + r7.xyz;
```

**Comment by dnblank123** [comment]
Thanks again, now it's working, the particles are aligned.
![image](https://github.com/bo3b/3Dmigoto/assets/67945097/ccdfc29f-4f48-410a-af3b-28ef8974da41)

Also, is there a better way to handle a lot of hashes? since there's a lot of misaligned particles I need to add or fix. For example:
```
[ShaderOverrideParticleVS2]
Hash=e81c1290bd57fc0f
x3 = ps-t0
x4 = ps-t0
[TextureOverrideSwordParticle2]
hash = f599c7e6
filter_index = 3
[TextureOverrideSwordParticle3]
hash = 3d7355ce
filter_index = 4

to 

[ShaderOverrideParticleVS2]
Hash=e81c1290bd57fc0f
x3 = ps-t0
x4 = ps-t0
[TextureOverrideSwordParticle2] // I assume no? or similar functionality to this?
hash = f599c7e6
filter_index = 3
hash = 3d7355ce
filter_index = 4


```
 
 In the shader: 
```
// is it possible to use one variable only or the only way is multiple variable?
  float4 particle = IniParams.Load(int2(3, 0));
  float4 particle2 = IniParams.Load(int2(4, 0));
  
   if(particle.x == 3) // I tried (particle.x == 3 && particle.y == 4) it doesn't work for some reason.
  {
     r7.xyz = r8.xyz * r7.xyz;
  }
  if(particle2.x == 4)
  {
     r7.xyz = r8.xyz * r7.xyz;
  }
```

**Comment by DarkStarSword** [comment]
> Also, is there a better way to handle a lot of hashes? since there's a lot of misaligned particles I need to add or fix. For example:

At the moment no, the way you are doing it is the right way.

Keep an eye on this space though - I want to add some sort of mechanism to allow modding communities with multiple modders to add ShaderOverrides in their individual mods that don't cause issues if another modder adds the same section (at the moment they have to coordinate so these go in a central file like the d3dx.ini and the modders then only add TextureOverride sections in their individual mods), and depending on how I end up implementing that we *might* allow for multiple hashes in the same section (the way I'm thinking it might work would allow each individual modder to re-open an existing central ShaderOverride section and append any additional hashes they need, for your case you would just add multiple hashes to a single section). If that is the solution I end up going with you still wouldn't be able to have multiple filter_index values in the section though, but you can make one section for each distinct type of adjustment you want with all the relevant shaders listed.

Let me know if you think that might be helpful - this idea has been mulling around in my mind for a while, but I haven't yet got around to implementing it.

**Comment by dnblank123** [comment]
I'm not sure if I got the gist of it, so in one TextureOverride section, you can add multiple hashes, and the filter_index will be separated. I think that would be helpful, but if other modders don't want it, I'm completely fine with it.

**Comment by dnblank123** [comment]
Closing it since the main issue has been solved. Thank you.
