### ISSUE TITLE
how can i run this successfully?

### ISSUE THREAD

**Issue by TAELVEY** [bo3b/3Dmigoto#185]
i replaced this target ,but it've been missing for a while...
![Desktop Screenshot 2023 12 21 - 17 24 54 94](https://github.com/bo3b/3Dmigoto/assets/140841077/d52bb7ac-e4b4-4333-a976-0427d7312001)

![Desktop Screenshot 2023 12 21 - 17 23 40 66](https://github.com/bo3b/3Dmigoto/assets/140841077/f0712bed-8eff-4d08-9fa2-252f854ded21)
is there someone can help me?

**Comment by bo3b** [comment]
You need to uncomment the lines for the loader to work.  The comment symbol is the semi-colon like ;
You delete the semi-colon to activate the line.

You need _target =_ and _module =_ at a minimum. Uncomment _launch =_ if you want the loader to auto-launch the game.

**Comment by DarkStarSword** [comment]
I'm going to close this issue since there hasn't been any activity recently. If you still need assistance feel free to re-open the ticket.
