### ISSUE TITLE
How do I tune d3dx.ini for playing?

### ISSUE THREAD

**Issue by xma23** [bo3b/3Dmigoto#186]
I am trying to force WOW client on exclusive full screen only. How do I modify the original ini file, which is tuned for hunting, for maximum performance? Thanks!

**Comment by DarkStarSword** [comment]
Main one is setting `hunting=0`

You can also turn off logging, exporting shaders, etc. The list of options I personally always make sure are set correctly before releasing a mod are here:
https://github.com/DarkStarSword/3d-fixes/blob/master/mkrelease.sh#L64

**Comment by xma23** [comment]
I tried with hunting off, scale on, full screen on, custom shader scale on, but Im getting black screen constantly, What am I missing?

**Comment by DarkStarSword** [comment]
Sorry, you got a black screen only after tuning the ini for performance?

If you were getting a black screen from the get go you should have led with that - there's no point tuning it for performance if it isn't working to begin with, unless you really want to squeeze all the fps you can out of that black screen :-p

Go back to the default ini file and enable debug logging (calls=1, debug=1), run the game, observe the black screen, then attach the d3d11_log.txt here

**Comment by DarkStarSword** [comment]
I'm going to close this issue since there hasn't been any activity in the last month. If you still need assistance feel free to re-open it and attach the requested log file.
