### ISSUE TITLE
Lots of null ptr checks on C++ new should be removed.

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#22]
As DarkStarSword observed, any 'new' allocation of C++ objects is going to throw a bad_alloc exception on failure, not return a nullptr.  So there is no need to check for nullptrs, and there is a need to handle exceptions.

A simple solution to avoiding the exception might be to just ignore them as part of hacking and extremely rare.

Another possibility is to change them to new (std::nothrow).

**Comment by DarkStarSword** [comment]
I can't find any of these left in the DX11 project, so I'm closing this.
