### ISSUE TITLE
iniParams not passed into shaders in 2D mode

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#23]
Reported here: https://forums.geforce.com/default/topic/685657/3d-vision/3dmigoto-now-open-source-/post/4631403/#4631403

With 3D fully disabled.

**Comment by bo3b** [comment]
Also shader partnering not functional. Will be worth looking to see if we can make it all work in 2D.

**Comment by masterotaku** [comment]
Not only that. "Handling=skip" also doesn't work (confirmed with a shader I was skipping in Zelda Skyward Sword). I suspect that all ShaderOverride possibilities aren't working in 2D.

**Comment by Janitor1** [comment]
Ah, that explains this problem:

https://forums.geforce.com/default/topic/685657/3d-vision/3dmigoto-now-open-source-/post/4568590/#4568590

I guess I should have mentioned I was trying to make a HUD toggle in 2D mode :P

**Comment by DarkStarSword** [comment]
This issue should be fixed in 3DMigoto 1.2.9
