### ISSUE TITLE
Crash on F10 reloads

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#25]
Report from Radek that combined F10 reloads of .ini and shaders crashes upon some of his games.  He separates .ini from shaders setting shaders to F8 to avoid the problem.

**Comment by DarkStarSword** [comment]
config reload crashes if 3D is disabled in the control panel - pretty certain the root cause is that ini params isn't set up in that case.

**Comment by bo3b** [comment]
Good to know.  Worth noting that Radek is using a no-nvapi setup so that it works on AMD cards. Fortunately we have enough flexibility that he can work around it and it doesn't affect his end users.

**Comment by DarkStarSword** [comment]
This issue should be fixed in 3DMigoto 1.2.9
