### ISSUE TITLE
Improve ternary if to exactly match asm 

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#28]
Current If statements get turned into HLSL 1/0, which is different than the ASM 0xffffffff/0x00000000.

` lt r2.xyzw, cb6[20].xyzw, r1.xxxx `
becomes
` r2.xyzw = g_CascadeSelectDist.xyzw < r1.xxxx;`

Which is not exactly right, because in ASM, r2 will be 0xfffffff or 0x00000000, and in HLSL r2 will be 0x00000001, or 0x00000000.

This does not generally cause problems, but in rare scenarios the difference matters.

We can make this better by making lt/gt/et. al. generate a ternary instead.

` r2.xyzw = (g_CascadeSelectDist.xyzw < r1.xxxx) ? -1 : 0;`

At the expense of code readability.  Somewhere in the 3Dmigoto game folders I made an example that uses a subroutine to keep the readability.

**Comment by DarkStarSword** [comment]
Closing this as it was fixed in 3DMigoto 1.2.14
