### ISSUE TITLE
Infinite Loops in AC3 HLSL

### ISSUE THREAD

**Issue by mikear69** [bo3b/3Dmigoto#3]
The following shaders have infinite loops:
1e64e5491f6f4898-ps_replace.txt
f30fe0c1c54c4952-ps_replace.txt

This code was generated as part of the HLSL in both shaders:

r0.w = 0.000000000e+000;
  while (true) {
  r1.w = (int)r0.w >= (int)4;
  if (r1.w != 0) break;
- which never terminates.

The same code also exists in 0967646d9a697258-ps_replace.txt, but this was not reported in the log as an infinite loop there were other errors instead which I think are a consequence of this one.

**Comment by bo3b** [comment]
Pretty sure this has long since been fixed, but it would be worth running a recent version like 1.2.9 against AC3 and make sure it's still working.  AC3 is our oldest fix, most likely to be broken.

**Comment by DarkStarSword** [comment]
Closing this old issue - if it still exists, feel free to reopen it.
