### ISSUE TITLE
3DMigoto crash on launch in FC4 on Windows 8.0 due to failure when requesting IDXGIAdapter2 interface

### ISSUE THREAD

**Issue by DarkStarSword** [bo3b/3Dmigoto#31]
Reported by pirateguybrush with 3DMigoto 1.2.9 using FC4 update WIP from github.

1.0.1 confirmed as working.

d3d11_log.txt is missing

nvapi_log.txt:

    NVapi DLL starting init - v 1.2.9 -  Mon Nov 16 19:29:30 2015
    
    
    [Logging]
      debug=1
      unbuffered=1  return: 0
    [ConvergenceMap]
    [Device]
      full_screen=1
    [Stereo]
      force_no_nvapi=0 
      force_stereo=0 
      automatic_mode=0 
      unlock_separation=0 
      surface_createmode=-1 
    Trying to load original_nvapi64.dll

API trace: http://darkstarsword.net/pirateguybrush-fc4.apmx64

~~At a first guess, looks like d3d11.dll either hasn't loaded (API trace shows it has), hasn't hooked LoadLibrary, or something (UPlay?) has interfered with the hook.~~

**Comment by DarkStarSword** [comment]
I suspect that the nvapi_log.txt is incomplete - API trace clearly shows the LoadLibraryEx("original_nvapi64.dll") call succeeds, and further calls suggest that our nvapi is communicating with the real one just fine. I've seen this before where nvapi_log.txt was incomplete even while using unbuffered=1 but haven't dug into it.

**Comment by DarkStarSword** [comment]
Actually looking at the source we don't print a message for successfully loading the original nvapi64.dll (I could have sworn we did), so there may not be anything amiss in the log after all.

**Comment by DarkStarSword** [comment]
Pirateguybrush reporting a hang on the FC4 splash screen in Windows 10. Until I know otherwise I'm lumping it in with the crash on Win 8.

**Comment by DarkStarSword** [comment]
API trace shows d3d11.dll should have made enough progress to produce a log file... Realised we were missing calls=1. Will get logs from a new run...

**Comment by DarkStarSword** [comment]
Suspect code path from the API trace:

    API	Return Value	Error	Duration
    IDXGIAdapter::CheckInterfaceSupport ( ID3D10Device, NULL )	S_OK
    D3D10CreateDevice ( NULL, D3D10_DRIVER_TYPE_HARDWARE, NULL, 0, 29, 0x000000bf652af000 )	E_INVALIDARG	0x80070057 = The parameter is incorrect.
    D3D11CreateDeviceAndSwapChain ( NULL, D3D_DRIVER_TYPE_HARDWARE, NULL, 1073741824, 0x000000bf652ae780, 1, 7, NULL, NULL, 0x000000bf652ae788, NULL, NULL )	E_INVALIDARG	0x80070057 = The parameter is incorrect.

Worth seeing what happens if we make CheckInterfaceSupport fail when asking about a DX10 device.

Another suspect code path:

    API	Return Value	Error	Duration
    CreateDXGIFactory ( IDXGIFactory, 0x000000bf652aba88 )	S_OK
    IDXGIFactory::QueryInterface ( IDXGIFactory2, 0x000000bf652aba78 )	E_NOINTERFACE	0x80004002 = No such interface supported
    IDXGIFactory::Release (  )	0

Since the game is running on Windows 8, it is quite reasonable for it to expect the Factory2 to work and may be treating the E_NOINTERFACE error we return as fatal.

**Comment by DarkStarSword** [comment]
d3d11_log.txt from Win 8 run:

[d3d11_log.txt](https://github.com/bo3b/3Dmigoto/files/35604/d3d11_log.txt)

Final message in the log is one of the calls where we tried to force a fallback path:

    HackerDXGIAdapter::QueryInterface(class HackerDXGIAdapter1@000000BE978D18B0) called with IID: IDXGIAdapter2 
      returns E_NOINTERFACE as error for IDXGIAdapter2. 

This might suggest that this approach may not work on Win 8.

**Comment by DarkStarSword** [comment]
Win 10 log:

[d3d11_log(1).txt](https://github.com/bo3b/3Dmigoto/files/35620/d3d11_log.1.txt)

Looks like a separate issue. Of note there appear to be several failures creating the stereo texture and ini params resources just before a final release of the device:

    HackerDevice::Release counter=1, this=000000D5DFAB45E0
      created NVAPI stereo handle. Handle = 000000D5E5504330 
      creating stereo parameter texture. 
        call failed with result = 80070057. 
      creating .ini constant parameter texture.
        CreateTexture1D call failed with result = 80070057.
    ->returns result = 0, device handle = 000000D5E5434440, device wrapper = 000000D5DFAB45E0, context handle = 0000000000000000, context wrapper = 0000000000000000 
    
    HackerDevice::Release counter=0, this=000000D5DFAB45E0
      deleting self

**Comment by DarkStarSword** [comment]
Log from win8 with 1.2.6. Different crash - looks like the GetImmediateContext bug I fixed recently so this is not relevant to the problem at hand. Still saving this so I don't lose track of the data point

[d3d11_log_win8_1.2.6.txt](https://github.com/bo3b/3Dmigoto/files/35634/d3d11_log_win8_1.2.6.txt)

**Comment by DarkStarSword** [comment]
A run on Win 8 using 3DMigoto 1.2.9 with commit d06a5ee543b1ff7df2d6147f7051eebc62922b57 (Add a QueryInterface call to HackerDXGIAdapter to return HackerDXGIAdapter1) reverted:

[d3d11_log_win8_1.2.9_adapter_queryinterface_reverted.txt](https://github.com/bo3b/3Dmigoto/files/35696/d3d11_log_win8_1.2.9_adapter_queryinterface_reverted.txt)

This time it behaved more like Windows 10 did in issue #32 (including the stereo + ini param creation failures). So, refusing the Adapter2 request is definitely fatal for this game on Win 8, then it looks like we have a separate issue to solve that affects both Win 8 + Win 10.

**Comment by bo3b** [comment]
I'm less sure about this.  I know for sure that I tried FC4 on my alt-game-machine running Win8.1, and it worked OK.

Also, it makes no sense that it's broken on Win8, surely we would have heard about this before now?

**Comment by bo3b** [comment]
BTW, I don't think that failing to create a D310 device is always significant. I very often see the QueryInterface fail as:

``` 
HackerDevice::QueryInterface(class HackerDevice@000000BE977775B0) called with IID: ID3D10Device 
  failed result = 80004002 for 000000BE96E886B8 
```
Where we don't do anything to change that call.  Same effect for the D3D9 variant.
Might be significant here because of the overlay and the earlier crash.

**Comment by DarkStarSword** [comment]
It appears to be a special case in Far Cry 4 that checks specifically for Windows 8.0 (not 10, not sure about 8.1) and asks for an IDXGIAdapter2, treating it as fatal if that fails because that is supposed to work on Win 8.0.

No one has reported it because the version on the blog is still using 1.0.1 from before we wrapped DXGI, and most other games will use a fallback path if the request for IDXGIAdapter2 fails. I asked pirateguybrush to test the pending update I want to release on the blog.

**Comment by bo3b** [comment]
OK, lots of funny code paths with games.  

Is it possible this is a game update?  Looking at it on the Win10 machine, I see the last few lines:

```
'FarCry4.exe' (Win32): Loaded 'C:\Windows\System32\dsound.dll'. Cannot find or open the PDB file.
'FarCry4.exe' (Win32): Loaded 'C:\Windows\System32\nvd3dumx.dll'. Cannot find or open the PDB file.
'FarCry4.exe' (Win32): Loaded 'C:\Windows\System32\dxdiagn.dll'. Cannot find or open the PDB file.
'FarCry4.exe' (Win32): Loaded 'C:\Windows\System32\D3D12.dll'. Cannot find or open the PDB file.
'FarCry4.exe' (Win32): Loaded 'C:\Windows\System32\msvcp110_win.dll'. Cannot find or open the PDB file.
The thread 0xbe4 has exited with code 0 (0x0).
Unhandled exception at 0x00007FFC2F23A28C (ntdll.dll) in FarCry4.exe: 0xC0000374: A heap has been corrupted (parameters: 0x00007FFC2F292180).
```
The crash is a corrupted heap.

It's interesting to note that it is trying to load D3D12.dll, which suggests a game update.

**Comment by DarkStarSword** [comment]
Interesting. I haven't seen any updated to FC4 in quite a few months... can't recall exactly when the last one was, but it was quite a while ago.

It may be an update to UPlay that's loading DX12 - I've seen both Origin and UPlay overlays try to load every version of DX and OpenGL on the planet, so it wouldn't surprise me if they have been updated for DX12, even if the game hasn't.

3DMigoto 1.1.x through 1.2.8 inclusive probably aren't worth trying on this game (or at least taking any results with a grain of salt) due to long standing bugs that were only just fixed in 1.2.9 - that was why I asked pirateguybrush to run a test version that had just a single suspect commit reverted instead ( https://github.com/bo3b/3Dmigoto/issues/31#issuecomment-157084993)

**Comment by DarkStarSword** [comment]
Run from Win 8.0 running in Win 7 compatibility mode - same problem with IDXGIAdapter2

[d3d11_log_1.2.9_win8_in_win7_compatibility_mode.txt](https://github.com/bo3b/3Dmigoto/files/36561/d3d11_log_1.2.9_win8_in_win7_compatibility_mode.txt)

**Comment by bo3b** [comment]
Looks like FC4 does not check the call result.  Since we set the adapter=null as part of the exit, they dereference that and crash. 

Seems like going upstream is probably better.  We can force a return at CreateDevice when they request 11_1.  Still might be being sloppy and just assume things will always be available, but it seems better to say we don't support higher levels as early as possible.

**Comment by bo3b** [comment]
Tried an interesting experiment with PirateGuyBrush, of forcing the device to be always DX11.  Didn't work, game is definitely looking for a hard-coded path for Win8 of some form.  Might be testing DXGI levels, and keying off of that.

**Comment by bo3b** [comment]
Ran across a different crash in Win7, with no evil update installed.  Looks like the game calls *CheckInterfaceSupport*, and crashes if that doesn't match the answer from CreateDevice.  If I return *DXGI_ERROR_UNSUPPORTED* for that one too, I can launch without problems.

I'll push up a change for this shortly.  Might be related to this Win8 crash.

**Comment by DarkStarSword** [comment]
Nice find :)

**Comment by bo3b** [comment]
OK, good news.  PirateGuyBrush tested an ENG build with the fix for CheckInterfaceSupport returning an error for anything other than D3D11, and it works.  

He can launch and play FC4 without a crash on Win8.

**Comment by DarkStarSword** [comment]
Great, thanks for that!

Screen depth reflections are nothing to worry about - pretty sure he was just using an old d3dx.ini with the 1.0.1 texture hashes

**Comment by bo3b** [comment]
@DarkStarSword Just a data point here, since this was a weird one-off bug I remembered.

Tried FC4 using 1.3 branch, set to allow all calls through unmodified with:

````
allow_check_interface=1
allow_create_device=1
allow_platform_update=1
````
Tried it on both Win10 and Win7 without evil update, and both worked without any crashes or errors.
