### ISSUE TITLE
Crash on Elite Dangerous

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#34]
Lastest version 1.2.12, here is the log.
[EliteD_d3d11_log.txt](https://github.com/bo3b/3Dmigoto/files/48087/EliteD_d3d11_log.txt)

Crashes at the first Present() call, all setup seems right.

**Comment by DarkStarSword** [comment]
Was wondering if it might be related to the overlay so I got andysonofbob to send logs with hunting=0 and hunting=2 as well:
[d3d11_log_Hunting0.txt](https://github.com/bo3b/3Dmigoto/files/88876/d3d11_log_Hunting0.txt)
[d3d11_log_Hunting2.txt](https://github.com/bo3b/3Dmigoto/files/88877/d3d11_log_Hunting2.txt)

Pretty much the same as hunting=1, so probably something else

**Comment by bo3b** [comment]
Since Nephilim has made a fix based on a released fix for AndySonOfBob, I think we can assume this one is fixed. :->

**Comment by bo3b** [comment]
Good point, I'll double check.

**Comment by bo3b** [comment]
Yup, my bad.  They are still using 1.0.1.

**Comment by bo3b** [comment]
OK, now I can close this out.  Version 1.2.53 fixes the crash at launch.
