### ISSUE TITLE
Feature request: Add the ability to handle keyboard modifiers like Ctrl, alt.

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#35]
Be worth having Alt-F1 be different from F1.  

Save conflicts in key mappings, and open up some possible other key modifiers.

**Comment by DarkStarSword** [comment]
For [Key] sections it is possible to achieve this with the condition setting on another ini param set (or cleared) by a second [Key] section while holding the modifier. We use this in MGSV to allow two different convergence presets on the F key depending on whether aim was being held when it is pressed.

This feature wasn't really intended to be used for this purpose (it is for use with scene detection), and it's not a complete solution - in particular I believe tonka wanted this for hunting key bindings, which don't support this as they are not [Key] sections.

I believe that tonka also wanted the bindings to only be used when a modifier was *not* being held, which is something to think about (what syntax do we use? which keys do we check are not being held - all of them, or just ctrl, alt, shift?).

**Comment by DarkStarSword** [comment]
Feature implemented for the next release, including combinations (e.g. "ctrl q") and exclusions (e.g. "no_alt f1", "no_modifiers f11", etc.)
