### ISSUE TITLE
warning meets when i was launching genshin.exe after

### ISSUE THREAD

**Issue by TAELVEY** [bo3b/3Dmigoto#352]
and the command keys were not work anymore

**Comment by TAELVEY** [comment]
![3DECE412736405EE9D1337258EB76451](https://github.com/user-attachments/assets/7d480f18-56d4-4281-8aa8-7d9e91900c1a)

**Comment by TAELVEY** [comment]
> and the command keys were not work anymore

i mean f1, f6, and f10

**Comment by TAELVEY** [comment]
the mod was attached successful though

**Comment by DarkStarSword** [comment]
This github is for 3DMigoto, not the GIMI fork or Genshin Impact mods - you are better off asking about this on their discord.

**Comment by TAELVEY** [comment]
> This github is for 3DMigoto, not the GIMI fork or Genshin Impact mods - you are better off asking about this on their discord.

sorry got it man
