### ISSUE TITLE
Marking not working in 0.59 Debug

### ISSUE THREAD

**Issue by mikear69** [bo3b/3Dmigoto#4]
Marking shaders is not working for me in 0.59 debug.  This may be related to the fact that F10 now is not crashing for me but does nothing at all, and the following is in the logs:

D3D11Wrapper::IDirect3DUnknown::QueryInterface called at 'this': class D3D11Wrapper::IDirect3DUnknown *

The above entry occurs hundreds of times.

**Comment by DarkStarSword** [comment]
Pretty sure this all works now - can we close this one out?

**Comment by bo3b** [comment]
Yeah, 0.59 was a loooong time ago.  

Marking and F10 work in the archived 1.0.1, and are working well with 1.2.9 in our latest code.
