### ISSUE TITLE
Replaced shader issues to investigate

### ISSUE THREAD

**Issue by DarkStarSword** [bo3b/3Dmigoto#40]
Looks like we may have a few bugs when replacing shaders that we need to investigate. I haven't looked into these yet, but am just adding my observations here for reference.

I've seen a number of shaders in ShaderCache with StereoParams declared twice in MGSV. Some of these may be related to hooking and using the wrong device internally to create shaders (using the hooked device instead of the trampoline device so 3DMigoto intercepts it's own shaders).

In KHOLAT (UE4 game, using wrapping) I dumped a vertex shader, modified it and reloaded, determined it was the wrong shader, deleted it and reloaded shaders, then dumped the same one again and found that it had used my modifications, and had StereoParams declared twice.

Also in KHOLAT after running a script to autofix a bunch of halo issues in various shaders I found that show_original was not using the original shaders. After moving everything in ShaderFixes out of the way and reloading shaders I hit this crash:

![revertmissingshadercrash](https://cloud.githubusercontent.com/assets/379749/12669643/49c4a86c-c6b6-11e5-9741-b9abe11794f3.png)

I had already worked on a number of shaders in KHOLAT, so the above steps may not be the full steps required to reproduce this.

I should note that I had started KHOLAT with dumping disabled initially, and only enabled it later (I think).

I also found after switching to a different Windows install that 3DMigoto can crash if there are permission problems on ShaderCache/ShaderFixes. I don't know the exact nature of these (I accidentally deleted TPP and had to redownload it).

**Comment by DarkStarSword** [comment]
DHR identified a repro case that results in duplicate StereoParams:

DSS i found a pattern for the StereoParams declared twice and other strange behavior.
- Go in to the game with a shader fixed
- While the game is running delete that shader and press F10 to see the effect back to original
- Don't quit the game and hunt again that shader and dump
- Now you should ear the boop sound, because the StereoParams is declared twice, also happens a few times that the shader dumped in the previous point is other different shader with the StereoParams declared twice.

Hope this can help

**Comment by oomek** [comment]
I found a weird behaviour during shader hunting. This is how to reproduce it:
1. dump a shader
2. add a shader ovverride section with the hash of the dumped shader
3. press F10
4. rename/delete the shader file
5. press F10 again
6. cycle through shaders
From this moment the shader is being skipped during hunting until you comment the shaderoverride section and the hash and press F10 again.

**Comment by DarkStarSword** [comment]
Just noting this here because I'm in the middle of something else and can't test it right now, but I suspect the reason we can sometimes dump out modified shaders instead of the originals are these lines in ReplaceShader():

    // New binary shader code, to replace the prior loaded shader byte code. 
    shaderCode->Release();
    G->mReloadedShaders[oldShader].byteCode = pShaderBytecode;

**Comment by DarkStarSword** [comment]
Some of the weirdness we have hit may be fixed by this commit:
https://github.com/bo3b/3Dmigoto/commit/0e272c6a8fad405f91cb82c30451b76196a5585a

That was a refcounting issue exposed by the new regex shader patching engine, however the refcounting bug existed without that and it is very conceivable that this could have caused us bizzare issues with certain combinations of replacing and reverting shaders. I expect the KHOLAT crash was almost certainly due to this.

**Comment by DarkStarSword** [comment]
The duplicate StereoParams (among other symptoms) bug is fixed in https://github.com/bo3b/3Dmigoto/commit/7f284fb08ab310ab3880086d8f2d177f7940b197

**Comment by DarkStarSword** [comment]
@oomek I am unable to reproduce your bug, but it occurs to me that you have used some tricks to thwart the timestamps that might be causing this problem... is it possible your ShaderOverride looks something like this:

    [ShaderOverrideFoo]
    hash = 0123456789abcdef
    run = CustomShaderFoo
    [CustomShaderFoo]
    vs = ShaderFixes/0123456789abcdef-vs_replace.txt
    draw = from_caller
    handling = skip

or similar (a draw= anywhere in there would be enough)? If so than I absolutely expect this behaviour because the replacement draw call will be outside of 3DMigoto's hunting code. Do let me know if you are able to reproduce it on a vanilla 3DMigoto without a draw= line.

I'm considering this bug closed for now. If there are still issues feel free to reopen.

**Comment by DarkStarSword** [comment]
DHR's bug was a different variant of the duplicate SteroParams issue, fixed in: https://github.com/bo3b/3Dmigoto/commit/a5821dd8ba6a5ee45604ac660750f4530d788dae

**Comment by oomek** [comment]
I've checked the issue with the latest build and it seems it's all true what you were saying about using the draw command in the override. Thanks for clarifying that.
