### ISSUE TITLE
AMD compatibility issue

### ISSUE THREAD

**Issue by oomek** [bo3b/3Dmigoto#45]
3DMigoto is failing to launch on Radeon cards if the original nvapi.dll is not present in one of the system directories.

**Comment by DarkStarSword** [comment]
Try removing the nvapi.dll / nvapi64.dll shipped with 3DMigoto

**Comment by oomek** [comment]
That doesn't help either, that was the first thing I've tried, and also setting no_nvapi=1
Radek






On Fri, Mar 25, 2016 at 8:52 AM -0700, "Ian Munsie" <notifications@github.com> wrote:












Try removing the nvapi.dll / nvapi64.dll shipped with 3DMigoto

**Comment by oomek** [comment]
When I rename the nvapi in windows\syswow64 back to original, it runs with or without 3DM nvapi.dll

**Comment by DarkStarSword** [comment]
Wait, what?

**Comment by oomek** [comment]
When you have both, nvidia and amd drivers installed it works, after renaming nvapi.dll from windows\syswow64 to nvapi.dll1 it doesn't. I've had it renamed for the time of testing, that's why I wrote renaming it back to original. Does that make sense now :)?

**Comment by oomek** [comment]
Just to be clear. This folder applies to x86 games, for x64 ones it will be windows\system\nvapi.dll

**Comment by oomek** [comment]
Ok, I've made all the possible tests on Radeon card with all the combinations and the results are as follows:

1. original nvapi.dll present in the system folder
3DM nvapi.dll present - game runs fine
3DM nvapi.dll not present - game runs fine

2. original nvapi.dll not present in the system folder
3DM nvapi.dll present - 2 (ligh-low) beeps, game not launching
3DM nvapi.dll not present - game launching, 3DM inactive

Setting force_no_nvapi to 0 or 1 has no effect in any case.
I hope that helps.

**Comment by oomek** [comment]
Here are the logs for the 3rd combination:

D3D11 DLL starting init - v 1.2.33 - Fri Mar 25 23:02:56 2016


----------- d3dx.ini settings -----------
[Logging]
  calls=1
[System]
[Device]
  get_resolution_from=swap_chain
[Stereo]
[Rendering]
  override_directory=D:\Downloads\1\ShaderFixes
  cache_directory=D:\Downloads\1\ShaderCache
  use_criticalsection=1
  rasterizer_disable_scissor=1
  stereo_params=125
  ini_params=120
  ... missing automatic ini section
[Hunting]
  hunting=1
  marking_mode=0
  analyse_options=log dump_rt_jps clear_rt
  repeat_rate=8
[Present]
[Constants]
  x7=0.00
Hooked_LoadLibraryExW switching to original dll: original_nvapi.dll to C:\WINDOWS\system32\nvapi.dll.


NVapi DLL starting init - v 1.2.33 -  Fri Mar 25 23:02:56 2016

[Logging]
  calls=1
[ConvergenceMap]
[Device]
  full_screen=1
[Stereo]
  force_no_nvapi=0 
  force_stereo=0 
  automatic_mode=0 
  unlock_separation=0 
  surface_createmode=-1 
*** LoadLibrary of original_nvapi.dll failed. *** 
Trying to load C:\WINDOWS\system32\nvapi.dll
*** LoadLibrary of C:\WINDOWS\system32\nvapi.dll failed. ***

**Comment by oomek** [comment]
There is a workaround for this issue found by Helifax.
3DM is working fine on Radeons when the proxy nvapi.dll is replaced with an original nvapi.dll from the system folder.

**Comment by bo3b** [comment]
If you get a chance, please try this experimental version of our nvapi64.dll.

This removes the error handling if it cannot find the original, and might work.  If it doesn't work, please make a debug log with debug=1, unbuffered=1.

[test_nvapi64.zip](https://github.com/bo3b/3Dmigoto/files/201259/test_nvapi64.zip)

**Comment by oomek** [comment]
Would it be much trouble to compile x86 version as well?

**Comment by bo3b** [comment]
[test_nvapi.zip](https://github.com/bo3b/3Dmigoto/files/201264/test_nvapi.zip)

These are just experimental, if it works, I'll make a real release.

**Comment by oomek** [comment]
The problem is that on my other machine I have quite small SSD drive so I test it on dx11 demos. I have not enough storage to install any game.

**Comment by oomek** [comment]
I wasn't able to find any x64 demo.

**Comment by oomek** [comment]
oh, sorry, I haven't sptted the attachment :)

**Comment by oomek** [comment]
Demo crashed unfortunately

D3D11 DLL starting init - v 1.2.33 - Sun Apr 03 11:09:44 2016
```
----------- d3dx.ini settings -----------
[Logging]
  calls=1
  debug=1
  unbuffered=1  return: 0
[System]
[Device]
  get_resolution_from=swap_chain
[Stereo]
[Rendering]
  override_directory=F:\1\ShaderFixes
  cache_directory=F:\1\ShaderCache
  use_criticalsection=1
  rasterizer_disable_scissor=1
  stereo_params=125
  ini_params=120
  ... missing automatic ini section
[Hunting]
  hunting=1
  marking_mode=0
  analyse_options=log dump_rt_jps clear_rt
  repeat_rate=8
[Present]
[Constants]
  x7=0.00
   Hooked_LoadLibraryExW load: original_nvapi.dll.
Hooked_LoadLibraryExW switching to original dll: original_nvapi.dll to C:\WINDOWS\system32\nvapi.dll.
   Hooked_LoadLibraryExW load: SUPPRESS_3DMIGOTO_REDIRECT.
   Hooked_LoadLibraryExW load: C:\WINDOWS\system32\nvapi.dll.
```


NVapi DLL starting init - v 1.2.35E -  Sun Apr 03 11:09:44 2016
```
[Logging]
  calls=1
  debug=1
  unbuffered=1  return: 0
[ConvergenceMap]
[Device]
  full_screen=1
[Stereo]
  force_no_nvapi=0 
  force_stereo=0 
  automatic_mode=0 
  unlock_separation=0 
  surface_createmode=-1 
Trying to load original_nvapi.dll 
*** LoadLibrary of original_nvapi.dll failed. *** 
Trying to load C:\WINDOWS\system32\nvapi.dll
*** LoadLibrary of C:\WINDOWS\system32\nvapi.dll failed. *** 
```

**Comment by bo3b** [comment]
[test2_nvapi.zip](https://github.com/bo3b/3Dmigoto/files/201275/test2_nvapi.zip)

OK, another experiment there.  This one sets up all the routine callbacks to be our routines.  Seems like this has a high chance of infinite loop, but prior crash is probably null ptr reference.  Just guessing here, code inspection debugging is not awesome of course.

**Comment by oomek** [comment]
Same behaviour unfortunately. The logs are identical so I won't be posting them.

**Comment by bo3b** [comment]
OK, thanks for trying those out.  Unfortunately that's all I can really see as making any sense here.  

Based on the Helifax experiment, that suggests that we need something from the actual nvapi that we can't otherwise live without.  Not sure, the startup sequence is seriously complicated. 

I guess for the time being keep using the workaround, even though it's a bit messy, it should be OK.  

If I can think of a way to debug this I'll get back to you.

**Comment by oomek** [comment]
Ok Bo3b, thanks for trying.

**Comment by psyke83** [comment]
Same issue with a Radeon R7 M260, but I was able to workaround the issue by renaming nvapi64.dll to "original_nvapi64.dll" and placing it along with the wrapper dlls in the game folder. Seems less messy than putting it in the system folder.

OT (apologies): I'm using this wrapper **only** to force The Witcher 3's borderless mode into exclusive fullscreen mode. The game itself doesn't allow the full-screen resolution that I want to be selected (1024x576, as my GPU is limited), but it doesn't apply the same enforcement to borderless mode. I was able to use the alt+enter key combination to force full-screen, but the latest patch seems to block window command keys.

The wrapper works perfectly for my needs, but I'm not sure if I've configured it optimally. From the default config, I only changed these params:

hunting=2 (setting to 0 seems to break the full screen functionality)
force_no_nvapi=1
full_screen=1
allow_windowcommands=1
stereo_params=-1
ini_params=-1

Should I set anything else to make sure the wrapper isn't doing anything unnecessary for my needs?

**Comment by bo3b** [comment]
That should be good for settings.  You'll also want the logging disabled:
  calls=0
  debug=0
  unbuffered=0

If hunting=0 works, that is slightly better, but won't impact performance very much at 2. At 1, it's a large impact as it draws on screen and keeps track of a lot of data.

You probably don't need force_nvapi=1, as you aren't using it, but I'm not completely clear on how this works, so go with what works.  Performance wise, the only impacts are from logging and hunting.

**Comment by psyke83** [comment]
Much appreciated. Just replying to correct a little inaccuracy; setting hunting=0 doesn't break the needed functionality - not sure why I had trouble with it before, but it works fine upon retesting.

**Comment by ToolB0xx** [comment]
So which one of these workarounds... works? Have an AMD 290x and having the exact same issue, testing all above methods.

**Comment by bo3b** [comment]
Sorry, don't have any hardware to test.  

Most likely case is to replace our nvapi64.dll with the original one from NVidia.  That will allow calls to go through and startup properly, and is reported to work above.

If that is not working for you, set calls=1, debug=1, unbuffered=1 in the d3dx.ini. Post the log file and I'll take a look.

**Comment by ToolB0xx** [comment]
Thank you bo3b, had a friend with an Nvidia gpu send over his nvapi64.dll and replaced it, worked fine then. Appreciate the help

**Comment by mirh** [comment]
nvapi.dll can be found in nvidia's drivers "Display.driver" folder.. 
If one is willing enough, you could try to *bisect* in which ever version they broke compatibility.

**Comment by DarkStarSword** [comment]
There are several problems here.

1. MAIN PROBLEM:
We have nvapi.dll / nvapi64.dll listed in our dependencies:

C:\cygwin64\home\dss\3DMigoto\x64\Zip Release>dumpbin /dependents d3d11.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24213.1
Copyright (C) Microsoft Corporation.  All rights reserved.


    Dump of file d3d11.dll
    
    File Type: DLL
    
      Image has the following dependencies:
    
        nvapi64.dll
        XINPUT9_1_0.dll
        D3DCOMPILER_47.dll
        KERNEL32.dll
        USER32.dll
        GDI32.dll
        SHELL32.dll
        ole32.dll
    
The Windows dynamic linker will discover that nvapi64.dll does not exist and will prevent us loading, and if the game was dynamically linked against d3d11.dll it will in turn prevent the game from loading.

This isn't how nvapi is supposed to work - we are supposed to statically link against nvapi.lib / nvapi64.lib and that library will load nvapi.dll / nvapi64.dll at runtime and return graceful errors if it could not.

The only reason that nvapi.dll is in our dependencies is because we directly call NvAPI_QueryInterface as a hack to tell our wrapper nvapi that the next call is us. NvAPI_QueryInterface is not an officially supported API and bypasses the static library. Commenting out that call alone removes the dll from our dependencies:

    C:\cygwin64\home\dss\3DMigoto\x64\Zip Release>dumpbin /dependents d3d11.dll
    Microsoft (R) COFF/PE Dumper Version 14.00.24213.1
    Copyright (C) Microsoft Corporation.  All rights reserved.
    
    
    Dump of file d3d11.dll
    
    File Type: DLL
    
      Image has the following dependencies:
    
        XINPUT9_1_0.dll
        D3DCOMPILER_47.dll
        KERNEL32.dll
        USER32.dll
        GDI32.dll
        SHELL32.dll
        ole32.dll

2. SECONDARY PROBLEM:
Our nvapi wrapper does DoubleBeepExit() if is unable to load the real nvapi[64].dll instead of failing gracefully. Removing the nvapi wrapper is sufficient to eliminate this.

**Comment by DarkStarSword** [comment]
These two issues are theoretically fixed in https://github.com/bo3b/3Dmigoto/commit/0e734d44c62cd0e4d5f2f82a2f5641318ce4aabd and https://github.com/bo3b/3Dmigoto/commit/d980bba9071a3199c862e792f78e107c0a70410f, which are slated for release with the upcoming 3DMigoto 1.2.66. I haven't tested these thoroughly (since I am using nvidia hardware), so I will need you to test.

@oomek - you're building from source right? Are you able to test this for me before the next release? In theory you should be able to drop in both d3d11.dll and nvapi[64].dll from 3DMigoto and it should work on AMD, but if it doesn't work with both, try with only d3d11.dll.

**Comment by oomek** [comment]
My amd card is unfortunately stuck in my arcade cabinet i could move it to my desktop for a while, but i need to know if it requires uninstalling the nvidia drivers.

**Comment by DarkStarSword** [comment]
So you have both nvidia and AMD drivers installed?

It would be better to uninstall the nvidia driver - at a minimum nvapi64.dll should be removed from c:\windows\System32 and nvapi.dll removed from c:\windows\SysWOW64 to make it a valid test, but I don't know what consequences there would be for only partially removing the driver.

**Comment by oomek** [comment]
Yes I’ve got both drivers installed on my main pc. but don’t worry. I will install Steam on my Mame cabinet and get back to you.

**Comment by bo3b** [comment]
Another possible test case would be to use built-in Intel GPU.  Should be similar model as AMD for this purpose.

Sorry about breaking that compatibility with NvAPI_QueryInterface when I was creating the force_no_nvapi, it didn't even occur to me that it would not be part of the static link library- or that it will still link without half-in/half-out.  Nice find.

**Comment by oomek** [comment]
eeeerm, D3DCompiler_46 compiles only to about 130kb

**Comment by oomek** [comment]
I compile using VS2015 with projects set to VS2013

**Comment by DarkStarSword** [comment]
Don't build the d3dcompiler project in 3DMigoto - that's a wrapper we can optionally use for games that compile shaders from HLSL on the fly (which is extremely rare because of how slow that is) and a few special cases where a game loads d3d11.dll too late for us to hook into certain calls. If you build the DirectX11 project in "Zip Release" configuration it will copy in d3dcompiler_46.dll from the Windows SDK

**Comment by oomek** [comment]
Oh, Wasn’t aware of the zip release configuration. Will check it in a sec.

**Comment by oomek** [comment]
The recent build is working on AMD card without any issues in both situations: with your nvapi.dll plus original_nvapi.dll and with just original nvapi.dll copied over your one. It fails with the black screen with only 3dm files but that's to be expected.

If for any reason you wold like to peek on the logs here are all 3 situations zipped:
[logs](https://mega.nz/#!7sFVGYDD!pbjnVoKV33kg5YWX8JHWiugjJG9Pux56NW9WBvepqIs)

**Comment by DarkStarSword** [comment]
Did you try with no nvapi.dll at all - not 3DMigoto's and not nvidias?

> It fails with the black screen with only 3dm files but that's to be expected.
No, that's not expected at all. Thanks for testing though - that shows we still have more bugs to find.

**Comment by oomek** [comment]
It's working without nvapi :)
[log](https://mega.nz/#!XsV10ZBJ!5J2O-k-WY-8fcVkJ685HbiM1ez4pFZIowjDApFkhXQ4)

**Comment by DarkStarSword** [comment]
A fix for the crash when both our d3d11 and nvapi wrappers are present is now in master and scheduled for the upcoming 1.3.15 release, so I'm closing this issue.
