### ISSUE TITLE
Switch d3dx.ini reading API

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#47]
The current API is the super old one from Win16.  We are using calls like GetPrivateProfileString. The problem is that it opens and closes the file for every read operation, and there is no way to keep it open.  This makes it very slow for automated fixes, where there may be 1000 entries.

Might make sense to use the Boost version, which puts them all in a property-tree list. http://www.boost.org/doc/libs/1_61_0/boost/property_tree/ini_parser.hpp

There is also a simple reader class that is less heavyweight, key-value pairs: https://github.com/benhoyt/inih

**Comment by DarkStarSword** [comment]
We will need to make sure whichever API we choose respects the order of entries in the file, since that has become important in fixes that use anything from CommandList.cpp.

**Comment by DarkStarSword** [comment]
Done - will be included in 3DMigoto 1.2.64. This had became a significant problem in Dreamfall Chapters which was taking upwards of two minutes to parse the d3dx.ini. The new parser finishes in under a second.
