### ISSUE TITLE
Exclusive fullscreen only version

### ISSUE THREAD

**Issue by scj643** [bo3b/3Dmigoto#50]
I was looking into this since Nvidia mobile gpus have weird tearing issues when games don't run in exclusive fullscreen mode. This looks like it can do what I want but I don't need any of the 3d aspects of it.

**Comment by DarkStarSword** [comment]
We aren't going to maintain a fork without 3D support since that is the main function of the tool, but it shouldn't hurt to use it with 3D support left in either - it works just fine if 3D Vision is disabled through the control panel, and can even be made to run on ATI cards.

**Comment by scj643** [comment]
The reason for this is so that we could have versions for games that use direct X 9 since nothing seems to do that

**Comment by bo3b** [comment]
No, sorry, 3Dmigoto does not support DX9.  You might look at HelixMod which does.  If you are just looking for forced fullscreen there are a couple of other modding tools that do that. (Helixmod and others are not open source)

**Comment by scj643** [comment]
My goal is to get the sims 3 to run in exclusive mode

**Comment by bo3b** [comment]
Doing a quick google scan, it looks like the game normally uses exclusive full screen mode when you select full screen from the in-game options.  As contrasted with the windowed-fullscreen mode that some games support. Alt-Enter makes it swap windowed to fullscreen. Did this change?

**Comment by scj643** [comment]
The issue is that with a mobile GPU if it's not using true exclusive full screen you get a diagonal tearing. The sims doesn't actually use exclusive full screen since the tearing is noticeable.
