### ISSUE TITLE
Add DrawCall counting

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#51]
Often a question arises for performance.  Especially in newer games that seem to be more fully using the GPU.

Since we've already wrapped all DrawCalls, it would be interesting to monitor the pipeline here and see how many Draw Calls are being dispatched per frame.  

That could give us some insight into how close that bottleneck is being hit, especially in the 3D case.

(could also add a free frame rate counter, since we already hook present()).

**Comment by DarkStarSword** [comment]
We can already do this - just set analyse_options=log and activate frame analysis, then grep the resulting log.txt for ^Draw and ^Dispatch. Unless you want something more explicit?

**Comment by bo3b** [comment]
I was thinking more of a real-time and on-screen measure of DrawCall count, as a performance question.  Using logging would impact the performance.  

The idea is that some games on some systems have serious drops in performance, beyond the 2x expected.  Both GPU and CPU are at low % use.  It's possible this is the so-called DrawCalls bottleneck, and it would be interesting to have a tool to measure that.

https://forums.geforce.com/default/topic/968321/3d-vision/enabling-3d-causes-70-85-fps-drop-in-certain-games-/

Not exactly the usual task for 3Dmigoto, but I don't know of any other tool to measure this.
