### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by oomek** [bo3b/3Dmigoto#57]
I'm having a hard time compiling 3DM in VS 2013. there is a file called d3d10sdklayers.h, but in 8.1 kit folder. Do I miss some of the kits or should I switch the project to use 8.1 somehow?
here's the log:
1>------ Rebuild All started: Project: DirectXTK_Desktop_2013, Configuration: Debug Win32 ------
2>------ Rebuild All started: Project: D3D_Shaders, Configuration: Debug Win32 ------
3>------ Rebuild All started: Project: BinaryDecompiler, Configuration: Debug Win32 ------
1>  pch.cpp
3>  reflect.cpp
2>  Shaders.cpp
1>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
3>  decode.cpp
4>------ Rebuild All started: Project: NVAPI, Configuration: Debug Win32 ------
2>  Assembler.cpp
3>  Generating Code...
4>  DllMain.cpp
4>d:\dropbox\sources\3dmigoto-master\nvapi\main.h(9): fatal error C1083: Cannot open include file: 'Shlobj.h': No such file or directory
3>  BinaryDecompiler.vcxproj -> D:\Dropbox\Sources\3Dmigoto-master\x32\Debug\BinaryDecompiler.lib
2>  Generating Code...
2>  D3D_Shaders.vcxproj -> D:\Dropbox\Sources\3Dmigoto-master\Debug\D3D_Shaders.exe
5>------ Rebuild All started: Project: DirectX11, Configuration: Debug Win32 ------
5>  ResourceHash.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  CommandList.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  Override.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  Overlay.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  nvprofile.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  Input.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  IniHandler.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  Hunting.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  HookedDXGI.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  HookedDevice.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  HookedContext.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  HackerDXGI.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  HackerDevice.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  HackerContext.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  FrameAnalysis.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  DLLMainHook.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  D3D11Wrapper.cpp
5>c:\program files (x86)\windows kits\8.0\include\um\d3d10.h(6774): fatal error C1083: Cannot open include file: 'd3d10sdklayers.h': No such file or directory
5>  DecompileHLSL.cpp
5>  Assembler.cpp
5>  crc32c.cpp
5>  Generating Code...
========== Rebuild All: 2 succeeded, 3 failed, 0 skipped ==========

**Comment by bo3b** [comment]
It looks to me like something is broken with your installation.  In my 8.0 Windows Kit, I see the file "d3d10sdklayers.h" next to the caller "d3d10.h".  Also "Shlobj.h" is found in my "C:\Program Files (x86)\Windows Kits\8.0\Include\um"

But also, we never use "d3d10.h" for any of the files, so I don't know why it would be trying to fetch that.  Could be some long string of includes however.

We only use the 8.0 SDK, the 8.1 is problematic because the dissassembler is completely different.

I'd try reinstalling the 8.0 SDK from scratch.

**Comment by DarkStarSword** [comment]
FWIW I had some difficulty trying to get the Win 8.0 SDK installed on my Win 10 box... I have a topic branch 'vs2015' set up which is a work in progress porting to VS2015 + Win 10 SDK, however note that both the decompiler and disassembler are broken in that port (when I use it I only use export_binary=1 and use cmd_Decompiler to disassemble/decompile the shaders instead).

**Comment by oomek** [comment]
Windows 8.0 SDK came with the VS, so I assumed it's complete. Reinstalling it manually did the trick, thanks.

**Comment by DarkStarSword** [comment]
Good to know. Closing this issue.

**Comment by oomek** [comment]
I'm on Win 10 VS2013. In VS2015 it fails like you said, but I don't remember the speciffic error

**Comment by DarkStarSword** [comment]
You can use VS2015 to compile the master branch (and provides a debugger with better compatibility than VS2013), but it still needs VS2013 installed as well since it still needs the older toolchain.

**Comment by oomek** [comment]
Ooh, i've tried it first in VS2015, then installed VS2013. Good to know I can use VS2015 now.
