### ISSUE TITLE
Frame convergence/separation in shader override

### ISSUE THREAD

**Issue by llyzski** [bo3b/3Dmigoto#66]
In order to support automatic convergence by detecting specific scene (for example, low convergence for menu), it must support setting convergence/separation for the whole frame when some vs/ps pair is being used in that frame, and restore original pair when such vs/ps pair is not used.

This is supported in helix d3d9 shader override, in which you set convergence/separation pair in a shader override and the whole frame will use the custom value pair. Users do not have to manually press a key to switch convergence when the override is in place.

But currently in 3Dmigoto the convergence/separation value in shader override is only set for one single draw call and is restored after the draw call. This cannot be used to support automatic convergence for the whole frame. Thus new FrameConvergence/FrameSeparation values are needed in order to bring back the old helix feature.

**Comment by llyzski** [comment]
Here is my idea, pretty much the same as what is already in helix mod:

1. Add Preset* sections to specify one or more preset overrides. For example:

<pre>
[PresetMenu]
separation = 1.0
convergence = 0.3
transition = 250
transition_type = linear

[PresetCutscene]
separation = 1.0
convergence = 0.2
z = 0.0
</pre>

2. Reference the presets in ShaderOverride* or TextureOverride* sections. For example:

<pre>
[ShaderOverrideMenu1]
Hash = xxxxx
Preset = Menu

[ShaderOverrideMenu2]
Hash = xxxxx
Preset = Menu

[TextureOverrideCutscene1]
Hash = xxxxx
Preset = Cutscene

[TextureOverrideCutscene2]
Hash = xxxxx
Preset = Cutscene
</pre>

When any of the shader or texture overrides is activated in a scene, the preset override is activated automatically. If more than one preset override is activated then the last one is used. When no preset override is activated, the override is restored to previous values.

Any comments?

**Comment by llyzski** [comment]
I have started working on the implementation as suggested above. I will post here if I have any obstacles, is it ok? @bo3b

**Comment by llyzski** [comment]
OK, done with the preset for shader override, here is my changes, please take a look:

https://github.com/llyzski/3Dmigoto/tree/preset_override

**Comment by bo3b** [comment]
Took a quick look, and it seems really promising.   I don't see anything immediately that would cause us any problems.

Let me take a deeper review in the next day or so.

Please go ahead and create a pull request.  Here is a quick tutorial in case it's helpful: https://yangsu.github.io/pull-request-tutorial/

Thanks.

**Comment by llyzski** [comment]
OK I have created a PR here: https://github.com/bo3b/3Dmigoto/pull/67

I have also used this in NieR:Automata, setting automatic convergence for menu and cutscene. I have been playing it for a while now and it works great. The changes is as following in case you want to test. Now I don't have to push a key when viewing the map. :) Hopefully this can be included in the next version of the fix too.

<pre>
[PresetMenu]
separation = 5.0
convergence = 1.2

[PresetCutscene]
separation = 1.0
convergence = 0.3

[ShaderOverridePresetMenu1]
Hash = 8dce144c6b991189
Partner = 64390dbdcc8ca932
Preset = Menu

[ShaderOverridePresetCutscene1]
Hash = 62dcb353c7b93621
Partner = 096528e476816610
Preset = Cutscene
</pre>

**Comment by bo3b** [comment]
Sorry for the delay, I'll be looking at this today.

**Comment by llyzski** [comment]
Thanks for reviewing and merging!

**Comment by bo3b** [comment]
Created a new release, 1.2.62 that includes your code.  

I'll leave it up to you to announce the feature and availability.  You'll probably want to give some instructions on how to use it.

Usually for a release, we'll add a post to the main 3Dmigoto thread. Please go ahead and let people know there.  Easiest way to copy our format is to quote a release from either me or DarkStarSword, and you can copy the formatting.

[https://forums.geforce.com/default/topic/685657/3d-vision/3dmigoto-now-open-source-/93/](url)

**Comment by llyzski** [comment]
I think I can create a wiki page first before announcing it. :)

**Comment by llyzski** [comment]
Done: https://github.com/bo3b/3Dmigoto/wiki/Auto-preset-and-scene-detection
