### ISSUE TITLE
Will not run on Win8.1 Update 1

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#7]
zig11727 reports that it fails to run. 

Full logging:

```
DXGI DLL starting init  -  Sun Apr 13 19:15:12 2014

  unbuffered=1  return: 0
CPU Affinity forced to 1- no multithreading: true
DXGI DLL initialized.
CreateDXGIFactory1 called with riid=770aae78-f26f-4dba-a829-253c83d1b387
  routing call to CreateDXGIFactory2 with riid=770aae78-f26f-4dba-a829-253c83d1b387
CreateDXGIFactory2 called with riid=770aae78-f26f-4dba-a829-253c83d1b387
  calling original CreateDXGIFactory2 API
  failed with HRESULT=80004002
```

E_NoInterface, so the factory itself has somehow changed.  Thanks Microsoft.

**Comment by DarkStarSword** [comment]
Can we close this one out?

**Comment by bo3b** [comment]
Seems OK. I don't think either 1.0.1 or 1.2.9 have any specific problem with 8.1.

Any problems we have now are definitely game specific, not an overall flaw.  We still crash on a couple of games in Win10, but given the fixes should more likely deserve specific issues.
