### ISSUE TITLE
Dumped dds depth buffers won't open in Photoshop

### ISSUE THREAD

**Issue by oomek** [bo3b/3Dmigoto#76]
I do not know why but many dds files especially the depth buffers with msaa enabled refuse to open in Photoshop.

**Comment by bo3b** [comment]
Best bet is to use the 'texconv' tool from the DirectXTK.

Some details:
https://forums.geforce.com/default/topic/685657/3d-vision/3dmigoto-now-open-source-/post/5083065/#5083065

**Comment by oomek** [comment]
What a shame, I must have missed that post. Will try that tool, thanks.
