### ISSUE TITLE
_spyMgr.CreateProcess crashes at launch

### ISSUE THREAD

**Issue by bo3b** [bo3b/3Dmigoto#77]
Sorry to bug you here again.  This is probably answered on the old forums, but I'm stuck.

I'm getting a crash at launch while using Deviare2:

First-chance exception at 0x004F2B75 in limbo.exe: 0xC0000005: Access violation reading location 0x00000000.

>	win32u.dll!_NtUserCallOneParam@8()	Unknown
 	limbo.exe!0044fd9a()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for limbo.exe]	
 	limbo.exe!004457ac()	Unknown
 	uxtheme.dll!ClassicSystemParametersInfoA()	Unknown
 	uxtheme.dll!_InternalSystemParametersInfo()	Unknown
 	uxtheme.dll!ThemeSystemParametersInfoA()	Unknown
 	user32.dll!__EndUserApiHook@0()	Unknown
 	limbo.exe!00478878()	Unknown
 	limbo.exe!00739980()	Unknown
 	ntdll.dll!_NtClose@4()	Unknown
 	KernelBase.dll!CloseHandle()	Unknown
 	kernel32.dll!@BaseThreadInitThunk@12()	Unknown
 	ntdll.dll!__RtlUserThreadStart()	Unknown
 	ntdll.dll!__RtlUserThreadStart@8()	Unknown

The game is Limbo, running from the GoG version, which means there is no DRM or other foolishness.

I trimmed the C# code down to a minimal example, which is just the launch itself, no DLL load, and it still crashes.  This also crashes when run as Admin.  All Deviare 2.8.3 DLLs are in the app launch folder, and the DLLs are regsvr32 active.

````
            _spyMgr = new NktSpyMgr();
            hresult = _spyMgr.Initialize();
            if (hresult != 0)
                throw new Exception("Deviare initialization error.");

            // Launch the game, but suspended, so we can hook our first call and be certain to catch it.
            _gameProcess = _spyMgr.CreateProcess(@"G:\Games\limbo\limbo.exe", true, out continueevent);
            if (_gameProcess == null)
                throw new Exception("Game launch failed.");

            _spyMgr.ResumeProcess(_gameProcess, continueevent);

````

Bit of a loss here, any suggestions?

**Comment by DarkStarSword** [comment]
I'm a little confused - is this a deviare bug that affects 3DMigoto and this is our mirror of the report?

**Comment by bo3b** [comment]
Ha! Whoops!  Wrong repo.  Probably need some sleep.  Completely unrelated, for a different project altogether.  This is the Deviare version, not the in-proc version we use on 3Dmigoto.
