### ISSUE TITLE
Looking for source of these wrapper files

### ISSUE THREAD

**Issue by Keith94** [bo3b/3Dmigoto#79]
I found this archive: [d3dx.zip](https://github.com/bo3b/3Dmigoto/files/1312719/d3dx.zip) somewhere on the Helix Mod website, I'm interested to know if those files belong to an older version of 3Dmigoto? If so is there an official link/page (i.e. github) where those files can be downloaded from (specifically I didn't see the same d3d9 wrapper here)? Any help is appreciated.

**Comment by DarkStarSword** [comment]
That looks like an old version of Chiri's resolution forcing tool I think - we don't have the source code to that specific version, but from what I can tell that morphed into what is now 3DMigoto, so you can find the source code here with history going back to the original open source release, though beware that we are only maintaining the DirectX11 and NVAPI projects and the others have very likely bit-rotted and will need some work to get compiling or running without crashes.

And beware that even if you can get it running the DX9 project is very barebones - it has Chiri's resolution override code and provides logging, but very little else. Bo3b updated the DX10 project some time ago as an experimental version and was able to get it to wrap some games, but it isn't considered supported either.

I did notice that someone had forked 3DMigoto a while back and had done some work on the DX9 project, which may be of interest:
https://github.com/bo3b/3Dmigoto/pull/39

**Comment by Keith94** [comment]
Cool thanks for all the info! I found the page after a quick search [here](http://helixmod.blogspot.ca/2013/02/chiris-force-certain-resolutionhertz.html) and it looks like the proper one.

I tested the tool with one DX9 game so far, and it works but introduces some weird lag issues... it's unfortunate because the refresh rate override is a very useful feature for me.

Hmm I never complied any project before but if you know of any similar tools with refresh rate/resolution overrides, please let me know! :)
