### ISSUE TITLE
Mafia III crash on startup

### ISSUE THREAD

**Issue by Keith94** [bo3b/3Dmigoto#80]
I configured these options for Mafia III (to override the game's 60 Hz refresh rate):

>refresh_rate=120
>full_screen=1

But the game fails to start properly most of the time.
In case there's a way to fix it here's my d3d11_log (if that helps): https://pastebin.com/3vR5tmMc

**Comment by DarkStarSword** [comment]
I don't have Mafia III, but I have had some similar issues with the refresh rate override myself trying to force 60Hz for 3D TV Play, but I've never quite got around to investigating why.

You're forcing 120Hz - is this for 3D Vision or 2D? For 3D Vision if the game is set to 60Hz I think that is per eye, so 120Hz total. There's also the "Apply this refresh rate to all games" checkbox in the NVIDIA control panel's test stereoscopic 3D dialog that might help.

**Comment by Keith94** [comment]
>is this for 3D Vision or 2D?

In my case this is only for 2D.

>I have had some similar issues with the refresh rate override myself

Yeah, from my testing in Mafia III, the `refresh_rate=120` doesn't do anything unless `full_screen=1` is set, but the latter makes the game close silently right after launching. Is there a way to possibly debug that?

>There's also the "Apply this refresh rate to all games" checkbox

I've used the Nvidia feature before, but it has a long delay when launching/alt+tabbing from the game. A wrapper solution like 3Dmigoto/SpecialK is generally preferred.

**Comment by bo3b** [comment]
You shouldn't need the `full_screen=1`, if you can set full screen in the game settings. Exclusive full screen, not borderless.  Setting the frequency can only be done with exclusive full screen, because otherwise it's just a window, and the game has to follow whatever the monitor is using.

According to: https://pcgamingwiki.com/wiki/Mafia_III#Video_settings

You should be able to set it to 'unlimited', then set your monitor to just be at 120Hz, and not need any injector or tool.

**Comment by Keith94** [comment]
I believe the 'unlimited' setting is only for the _frame rate_ cap, whereas the game still chooses a 60 Hz refresh rate despite your monitor running at a higher frequency. Enabling `refresh_rate=120` by itself seemed to be ineffective at overriding the refresh rate (this is with exclusive fullscreen), hence the bug report. :P

**Comment by bo3b** [comment]
It doesn't make logical sense that there is an 'unlimited' option that is capped at 60 Hz.  

That's not how vSync works.  If you are stuck at 60 Hz, then you are not successfully disabling vsync.  There are at least three spots where this can be locked on, including the driver, so you'll need to experiment and learn how this all works.

In any case, this is not our bug, your configuration is not set up properly.  You should not need 3Dmigoto for this game.
