### ISSUE TITLE
Random shaders occasionally messed up after F10 reload

### ISSUE THREAD

**Issue by DarkStarSword** [bo3b/3Dmigoto#86]
I'm not positive if this is a 3DMigoto bug, a driver bug, a game bug, a corrupt shader or some combination thereof but I've seen it happen often enough that it deserves a bit more investigation and it (almost?) always seems to coincide with performing an F10 reload, which has me concerned that 3DMigoto may be contributing to it - but, it seems to affect random shaders - not ones that were actually reloading, and seems to happen even if only settings (and custom shaders) are being reloaded.

The types of glitches I've observed include things like:
- Certain surfaces going black
- Certain surfaces going nuclear (extremely bright overloading other bloom effects)
- Certain surfaces flickering like crazy (seen in ABZU)
- The entire world disappearing when the camera is pointed in specific directions (often to within a few degrees). Menu shaders always seem to be OK - possibly a corrupt lighting shader? (notably I haven't replaced any menu shaders in LiSBtS, but I have replaced lighting shaders)
- The world freezing in place, but post-processing effects (e.g. depth of field blur) continuing to work, suggesting they are using a valid depth buffer.
- An object appearing splayed over the camera (possibly corrupt vertex shader?)
- An inexplicable colour filter being applied (seen in ABZU)

I've seen these types of glitches happen in a number of games, but some are definitely more common than others. Life is Strange: Before the Storm seems to be triggering this way more often than any other game for some reason (currently on driver 376.33 with SLI on Windows 10), and has been happening even when I've only been reloading after messing with my own custom shaders. I also recall Lichdom Battlemage as being a game that triggered these type of glitches fairly often (much older driver on single GPU on Windows 7), and saw these happen in ABZU every now and then, and have occasionally seen them in other games as well.

show_original and marking_mode=original does not return these shaders to working versions, nor does attempting to replace them in ShaderFixes. Once these glitches occur, the only reliable way to recover seems to be to restart the game.

**Comment by DarkStarSword** [comment]
One possible explanation could be that 3DMigoto may be somehow replacing shaders with unrelated shaders. In theory, this could occur if a shader was released and another shader later gets the same memory handle and our data structures still have some state left over from the original shader. I can't see a way this could happen - while we don't clean up our data structures when a shader is released, we should be overwriting the entries in our data structures when the new shader is created, but it's worth double checking that we haven't missed something.

I'm thinking one experiment worth trying might be to tag the original and replaced shaders with matching IDs using SetPrivateData, and check that these IDs still match when we replace one.

**Comment by DarkStarSword** [comment]
Just had a really interesting one in Before the Storm, where the shader for Chloe's hair became transparent and caused some objects behind it to also become transparent, but from other camera angles switched to the shader that is supposed to be used for highlighted objects (which is one I had manually patched) - that's the clearest evidence so far that shaders may be being mixed up, not just corrupted/disabled or whatever:

![life is strange - before the storm - 2018-01-11 - 220804 0](https://user-images.githubusercontent.com/379749/34822938-aee288c0-f71c-11e7-8471-cb508971cb9d.jpg)

![life is strange - before the storm - 2018-01-11 - 220738 0](https://user-images.githubusercontent.com/379749/34822941-b1c326bc-f71c-11e7-9437-5d23049b2308.jpg)

**Comment by DarkStarSword** [comment]
Well, this is interesting - hunting mode (skip mode with verbose overlay so I could get the hash without dumping the shader and potentially altering our data structures) identified the hair pixel shader as c468bcdebfed1341:

![life is strange - before the storm - 2018-01-11 - 223132 0](https://user-images.githubusercontent.com/379749/34824386-56026b98-f722-11e7-9d10-d986fbe7d2c2.jpg)

My scripts identify as one of the variants of Hair/HairSpecular, which makes sense. But - this hash does not show up in the frame analysis log, in fact where it should be we see this instead:

    1.000470 VSSetShader(pVertexShader:0x00000000DB9FBEB8, ppClassInstances:0x0000000000000000, NumClassInstances:0) hash=72c66c36ec153f1d
    1.000470 PSSetShader(pPixelShader:0x00000000DB9F8678, ppClassInstances:0x0000000000000000, NumClassInstances:0)

That's right - ***3DMigoto does not know the hash for this shader***. ShaderUsage.txt does show the relationship between these shaders, so at some point in the past while hunting was enabled it did know the hash:

    <VertexShader hash="72c66c36ec153f1d">
      <CalledPixelShaders>b3d214c68cf2a400 c468bcdebfed1341 </CalledPixelShaders>

[log.txt](https://github.com/bo3b/3Dmigoto/files/1622424/log.txt)
[ShaderUsage.txt](https://github.com/bo3b/3Dmigoto/files/1622425/ShaderUsage.txt)

**Comment by DarkStarSword** [comment]
Damnit, the lack of hash in the frame analysis log may be due to the changes to improve performance of frame analysis - one of the problematic side effects of that change was that frame analysis will see the changed value from 3DMigoto, not the original value from the game. I'm tempted to revert that change, because this is exactly the type of situation I was concerned it would lead to and it only improved performance by <= 1fps.

Regardless, this hypothesis suggests that 3DMigoto *has* inappropriately replaced the shader for some reason.

**Comment by DarkStarSword** [comment]
d3d11_log.txt shows something interesting - despite never being replaced, 3DMigoto attempted to revert this shader on an F10 reload:

    HackerDevice::CreatePixelShader called with BytecodeLength = 5708, handle = 000000000B443040, ClassLinkage = 0000000000000000
           FNV hash = c468bcdebfed1341
        shader registered for possible reloading: c468bcdebfed1341_ps as bin -
      returns result = 0, handle = 00000000DB9F79B8

    ...

    > reloading *_replace.txt fixes from ShaderFixes
    Reverting 244b375ac9e44bf1 not found in ShaderFixes
    Reverting c468bcdebfed1341 not found in ShaderFixes
    Reverting f5fb54d6c9f2a467 not found in ShaderFixes
    Reverting 59095007ed62bdd3 not found in ShaderFixes
    Reverting 2b1e982392fa63ca not found in ShaderFixes
    Reverting f5fb54d6c9f2a467 not found in ShaderFixes
    Reverting 59095007ed62bdd3 not found in ShaderFixes
    Reverting f5fb54d6c9f2a467 not found in ShaderFixes
    Reverting f5fb54d6c9f2a467 not found in ShaderFixes
    Reverting a80560c74e90871b not found in ShaderFixes
    Reverting d11692f7c24ed5a4 not found in ShaderFixes
    Reverting b3d214c68cf2a400 not found in ShaderFixes
    Reverting f5fb54d6c9f2a467 not found in ShaderFixes

**Comment by DarkStarSword** [comment]
So, it appears that this sequence of events led to this bug:
1. The game creates a shader with hash 94a17e3186b7b635. 3DMigoto picks up a replacement shader from ShaderFixes and assembles it instead. The resulting shader is at address 00000000DB9F79B8. We store the original shader for possible later replacement in one of our data structures.
2. The game releases this shader. Since we do not hook or wrap the release call we don't see this and don't clean up the references to this shader in our data structures.
3. The game creates a shader with hash c468bcdebfed1341, which by chance gets the same memory address as the previous shader 00000000DB9F79B8. 3DMigoto does not find this shader in ShaderFixes, so does not replace it and does not update the original shaders map.
4. The user presses F10
5. 3DMigoto finds that there is no replacement shader with hash c468bcdebfed1341 in ShaderFixes, but since this shader shares the same handle as another that was replaced it reverts it to the original 94a17e3186b7b635 shader.

**Comment by DarkStarSword** [comment]
This bug should be fixed now, by checking for reused handles whenever we create a shader and erasing stale data. I'll still keep an eye out for it - if it's still present I'd expect it to reveal itself fairly quickly in Life is Strange: Before the Storm, but I'm pretty confident this is the correct fix.

**Comment by bo3b** [comment]
Nice catch.  Doing the hammer style seems fine to me, because creating and destroying shaders all the time should never be in the hot path.  I'd expect a little extra work at shader creation to be fine.
