### ISSUE TITLE
Mini Map Bug in .hack//G.U. Last Recode

### ISSUE THREAD

**Issue by BlueSkyDefender** [bo3b/3Dmigoto#90]
It seems that a transparency layer for the minimap bugs out and the entire minimap shows out of bounds areas.

I am only using to skip one shader in the game. 

[ShaderOverride1]
Hash=bbdad12117407f86
Handling=skip

Please note this does not affect the behavior of the minimap.

Picture of the issue.
https://cdn.pbrd.co/images/HbEOUPK.jpg

**Comment by DarkStarSword** [comment]
Try disabling rasterizer_disable_scissor in the d3dx.ini

Scissor clipping is generally not desirable in 3D (as it is inherently 2D), and you may find you still need it disabled for some effects - refer to the comment in the d3dx.ini for how to enable/disable it on a per-shader basis.

If the scissor clipping is affecting the HUD and you need it enabled, the easiest thing will be to leave the HUD at screen depth, as that is the only depth where the scissor rectangle will line up. If you do need it at another depth and cannot disable scissor clipping we will have to look into other alternatives (such as having 3DMigoto pass the scissor rectangle into the shader and performing your own clipping based on that).

**Comment by BlueSkyDefender** [comment]
Thank you, that worked.

A side question.

So say I want to rewrite a shader completely and inject my own shader code. As long the shader is global like toggled on DOF effect. I should be able to hijack it to do whatever my new shader wants. Right?

**Comment by DarkStarSword** [comment]
Yeah, you can rewrite a shader completely if you want - @oomek was doing something like this to make a graphics overhaul mod that among other things added Screen Space Reflections to a game that didn't have them originally.

Depending on what you are doing you can also inject an entirely new shader and run it whenever you need - you can see we ship several [CustomShader]s in the template d3dx.ini already that are triggered from the [Present] call, but you can write your own and trigger them from wherever you need, including other shaders. It's also possible to use these to modify the render state of an existing draw call (combine draw=from_caller and handling=skip in the [CustomShader]), or duplicate a draw call. This page has some more info (I just updated it a little bit, but there is still a lot of info that needs to be copied from the release notes where they were introduced):
https://github.com/bo3b/3Dmigoto/wiki/Injecting-custom-shaders

3DMigoto contains a very powerful command list implementation, that is essentially a mini programming language (not yet turing complete, but pretty close) that lets you manipulate DirectX state however you need.
