### ISSUE TITLE
3Dmigoto Overlay disable/enable

### ISSUE THREAD

**Issue by Metalape** [bo3b/3Dmigoto#99]
Hello! 

Maybe it is a stupid Question, but i couldn't find an Info how to disable the 3Dmigoto Overlay.
It's enabled all the Time. How can i turn it off? Whats the Hotkey?

Greetings,

Metalape

**Comment by DarkStarSword** [comment]
By default it is number pad 0, you can customise this via the toggle_hunting config value. If you set hunting=2 the overlay will start disabled, hunting=1 will start enabled.
